;;;; package.lisp

(DEFPACKAGE #:SCHEMEISH.FOR-MACROS
  (:DOCUMENTATION "Provides FOR-MACROS which expands to (EVAL-WHEN ...)")
  (:USE #:COMMON-LISP)
  (:EXPORT #:FOR-MACROS))
(DEFPACKAGE #:SCHEMEISH.NAMED-LET
  (:DOCUMENTATION "Provides an optionally named LET which can be used to write a locally recursive form.")
  (:USE #:SCHEMEISH.FOR-MACROS #:COMMON-LISP)
  (:EXPORT #:LET)
  (:SHADOW #:LET))
(DEFPACKAGE #:SCHEMEISH.ARGUMENTS
  (:DOCUMENTATION "Tools to translate scheme style argument lists to CL style argument lists.")
  (:USE #:SCHEMEISH.FOR-MACROS #:COMMON-LISP)
  (:EXPORT #:ARG-LIST->LAMBDA-LIST))
(DEFPACKAGE #:SCHEMEISH.SYNTAX
  (:DOCUMENTATION "Provides install/uninstall-syntax! for expanding [fn-value args...] => (funcall fn-value args...)")
  (:USE #:SCHEMEISH.FOR-MACROS #:COMMON-LISP)
  (:EXPORT #:INSTALL-SYNTAX! #:UNINSTALL-SYNTAX!))
(DEFPACKAGE #:SCHEMEISH.BASIC-SYNTAX
  (:DOCUMENTATION "Provides some basic syntax of scheme: FOR-MACROS NAMED-LET, [] reader syntax")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.SYNTAX
        #:SCHEMEISH.NAMED-LET
        #:SCHEMEISH.FOR-MACROS
        #:COMMON-LISP)
  (:EXPORT #:LET #:FOR-MACROS #:INSTALL-SYNTAX! #:UNINSTALL-SYNTAX!))
(DEFPACKAGE #:SCHEMEISH.EXPAND-DEFINE
  (:DOCUMENTATION "Tools to expand define and define-like forms.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:COMMON-LISP #:SCHEMEISH.BASIC-SYNTAX #:SCHEMEISH.ARGUMENTS)
  (:EXPORT #:EXPAND-FUNCTION-BODY #:EXPAND-TOP-LEVEL-DEFINE))
(DEFPACKAGE #:SCHEMEISH.DEFINE
  (:DOCUMENTATION "Provides DEFINE. See DEFINE's docs for more details.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.ARGUMENTS #:SCHEMEISH.BASIC-SYNTAX #:COMMON-LISP)
  (:EXPORT #:EXPAND-TOP-LEVEL-DEFINE #:DEFINE #:LAMBDA #:EXPAND-FUNCTION-BODY)
  (:SHADOW #:LAMBDA))
(DEFPACKAGE #:SCHEMEISH.BASE
  (:DOCUMENTATION "Provides many core functions and simple macros in addition to basic-syntax, including
  - symbols
  - lists
  - procedures
  - alists
  - sets
  - strings
  - output
  - mutation")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.DEFINE #:SCHEMEISH.BASIC-SYNTAX #:COMMON-LISP)
  (:EXPORT #:CONJOIN*
           #:PROCEDURE-ARGUMENTS-OPTIONAL-ARGUMENTS
           #:LAMBDA
           #:FOR-EACH
           #:SET!
           #:APPEND*
           #:MAP-SUCCESSIVE
           #:CONJOIN
           #:EXPAND-TOP-LEVEL-DEFINE
           #:EQ?
           #:FILTER-MAP
           #:SQR
           #:STREAM-REST
           #:INSTALL-SYNTAX!
           #:ALIST-VALUES
           #:DEFINE
           #:POSITIVE?
           #:SET-INTERSECT
           #:STREAM->LIST
           #:LIST-REF
           #:STRING-APPEND
           #:APPEND-MAP
           #:PROCEDURE-ARGUMENTS-REST-ARGUMENT
           #:STREAM-FOLD
           #:STREAM-REF
           #:TAKE
           #:FILTER
           #:STREAM-EMPTY?
           #:NULL?
           #:FOLDR
           #:XOR
           #:SORT
           #:MAP
           #:CONST
           #:RADIANS->DEGREES
           #:STREAM-DROP
           #:PROCEDURE-ARGUMENTS-REQUIRED-ARGUMENTS
           #:STRING-STARTS-WITH?
           #:DISJOIN
           #:MAKE-KEYWORD
           #:ALIST-KEYS
           #:NEGATIVE?
           #:SET->STREAM
           #:SUBSET?
           #:RANGE
           #:SET-UNION
           #:EXPAND-FUNCTION-BODY
           #:NUMBER->STRING
           #:PROCEDURE-ARGUMENTS-KEY-ARGUMENTS
           #:DISJOIN*
           #:STREAM
           #:REMQ*
           #:FLATTEN
           #:ODD?
           #:SYMBOL->STRING
           #:SET-REMOVE
           #:STREAM-CDR
           #:ALIST-SET
           #:LIST?
           #:FOR-MACROS
           #:RANDOM-STREAM
           #:REMQ
           #:ZERO?
           #:SET-SUBTRACT
           #:GROUP
           #:PARTITION
           #:DROP
           #:ORMAP
           #:STREAM-APPEND
           #:PAIR?
           #:FINDF
           #:PROCEDURE?
           #:SET-CDR!
           #:DISPLAY
           #:ALIST-HAS-KEY?
           #:THERE-EXISTS*
           #:STREAM-FIRST
           #:REMOVE*
           #:MEMF
           #:FOR-ALL
           #:UNINSTALL-SYNTAX!
           #:SYMBOL?
           #:FOR-ALL*
           #:NEWLINE
           #:LIST-TAIL
           #:ALIST-UPDATE
           #:SPLIT-AT
           #:ALIST-MAP
           #:EVEN?
           #:STREAM-MAP
           #:FORCE
           #:STREAM-CONS
           #:EMPTY?
           #:ALIST-REF
           #:LIST-SET
           #:SET=?
           #:ALIST-REMOVE
           #:SET-ADD
           #:STREAM-RANGE
           #:DISPLAYLN
           #:THERE-EXISTS
           #:STREAM-CAR
           #:STREAM-LENGTH
           #:PROCEDURE-ARGUMENTS
           #:STREAM-MAP-SUCCESSIVE
           #:FOLDL
           #:LIST->STREAM
           #:NOR
           #:LET
           #:NAND
           #:ALIST
           #:FILTER-NOT
           #:STREAM-FOR-EACH
           #:SWAP-ARGS
           #:NUMBER?
           #:ANDMAP
           #:DOCUMENT!
           #:*THE-EMPTY-STREAM*
           #:SET-EMPTY?
           #:PROCEDURE-ARGUMENTS-ALLOW-OTHER-KEYS?
           #:DEGREES->RADIANS
           #:STREAM?
           #:STREAM-FILTER
           #:HAS-SPECIFIC-ARITY?
           #:STREAM-FLATMAP
           #:PROCEDURE-ARITY
           #:STREAM-TAKE
           #:QUOTIENT
           #:ALIST-SET*
           #:LIST-UPDATE
           #:RCURRY
           #:LCURRY
           #:SGN
           #:DELAY
           #:SET-COUNT
           #:STRING?
           #:EQUAL?
           #:COMPOSE
           #:MEMO-PROC
           #:STREAM-FLATTEN
           #:SET-CAR!
           #:SET-MEMBER?)
  (:SHADOW #:MAP #:SORT #:STREAM))
(DEFPACKAGE #:SCHEMEISH.AND-LET
  (:DOCUMENTATION "Provides the and-let* macro.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:STREAM #:MAP)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:AND-LET*))
(DEFPACKAGE #:SCHEMEISH.EXPAND-STREAM-COLLECT
  (:DOCUMENTATION "Provides tools to expand a stream-collect macro form.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:MAP #:STREAM)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:STREAM-COLLECT-FORM))
(DEFPACKAGE #:SCHEMEISH.EXPAND-LEXICALLY
  (:DOCUMENTATION "Provides tools to expand lexically/expose macros.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:MAP #:STREAM)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:USE #:SCHEMEISH.AND-LET #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:LEXICAL-NAME->PARAMETER-NAME
           #:PARAMETER-NAME?
           #:PARAMETER-NAME->LEXICAL-NAME
           #:LEXICAL-BINDINGS
           #:SPECIAL?
           #:SPECIAL-FORM?))
(DEFPACKAGE #:SCHEMEISH.BUNDLE
  (:DOCUMENTATION "Provides bundle and make-bundle-predicate for creating dispatch-style closures.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:MAP #:STREAM)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:USE #:SCHEMEISH.AND-LET #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:BUNDLE-DOCUMENTATION
           #:BUNDLE?
           #:BUNDLE-LIST
           #:MAKE-BUNDLE-PREDICATE
           #:BUNDLE-PERMISSIONS
           #:BUNDLE))
(DEFPACKAGE #:SCHEMEISH.STRUCT
  (:DOCUMENTATION "Provides the basis and expansions for define-struct.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:STREAM #:SORT #:MAP)
  (:USE #:SCHEMEISH.AND-LET #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:STRUCT-COPY
           #:STRUCT->LIST
           #:STRUCT-ACCESSORS
           #:STRUCT?
           #:STRUCT-FORM
           #:STRUCT))
(DEFPACKAGE #:SCHEMEISH.STREAM-COLLECT
  (:DOCUMENTATION "Provides the stream-collect macro.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:STREAM #:MAP)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.EXPAND-STREAM-COLLECT #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:STREAM-COLLECT))
(DEFPACKAGE #:SCHEMEISH.DEFINE-STRUCT
  (:DOCUMENTATION "Provides define-struct.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:STREAM #:MAP #:SORT)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:USE #:SCHEMEISH.STRUCT #:SCHEMEISH.AND-LET #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:DEFINE-STRUCT))
(DEFPACKAGE #:SCHEMEISH.LEXICALLY
  (:DOCUMENTATION "Provides the lexically and expose macros.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:MAP #:STREAM #:SORT)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:USE #:SCHEMEISH.EXPAND-LEXICALLY
        #:SCHEMEISH.AND-LET
        #:SCHEMEISH.BASE
        #:COMMON-LISP)
  (:EXPORT #:LEXICALLY #:EXPOSE))
(DEFPACKAGE #:SCHEMEISH.QUEUE
  (:DOCUMENTATION "Provides a bundle-based implementation of a queue.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:STREAM #:MAP)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.BUNDLE #:SCHEMEISH.AND-LET #:SCHEMEISH.BASE #:COMMON-LISP)
  (:EXPORT #:MAKE-QUEUE
           #:QUEUE-EMPTY?
           #:QUEUE?
           #:QUEUE-FRONT
           #:QUEUE-DELETE!
           #:QUEUE-INSERT!))
(DEFPACKAGE #:SCHEMEISH.SERIALIZE
  (:DOCUMENTATION "Provides the serialize function which can recursively serialize lisp data, bundles, and structs
into a form ready for EVAL.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:STREAM #:MAP)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.QUEUE
        #:SCHEMEISH.DEFINE-STRUCT
        #:SCHEMEISH.STRUCT
        #:SCHEMEISH.BUNDLE
        #:SCHEMEISH.AND-LET
        #:SCHEMEISH.BASE
        #:COMMON-LISP)
  (:EXPORT #:SERIALIZE))
(DEFPACKAGE #:SCHEMEISH.PACKAGE-UTILS
  (:DOCUMENTATION "Provides tools for dealing with CL packages.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:STREAM #:MAP #:SORT)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:USE #:COMMON-LISP
        #:SCHEMEISH.QUEUE
        #:SCHEMEISH.DEFINE-STRUCT
        #:SCHEMEISH.STRUCT
        #:SCHEMEISH.BUNDLE
        #:SCHEMEISH.AND-LET
        #:SCHEMEISH.BASE)
  (:EXPORT #:SYMBOL-IN-PACKAGE?
           #:*RESOLVE-PACKAGE-DESIGNATOR*
           #:ALL-PACKAGES-WITH-STRING-PREFIX
           #:DEFPACKAGE-FORM
           #:FILTER-PACKAGES
           #:ENSURE-STRING
           #:INDEPENDENT-PACKAGE?
           #:NICKNAME-PACKAGE
           #:PACKAGE-DELETE
           #:PACKAGE-FILE-CONTENTS
           #:DEFINE-PACKAGE-FORM
           #:UNIQUE-PACKAGE-NAME
           #:WITH-TEMPORARY-PACKAGE
           #:PACKAGE-SHADOWING-IMPORT-FROMS
           #:PACKAGE-HIERARCHY
           #:PACKAGE-DEPENDENCIES
           #:SYMBOLS-IN-PACKAGE
           #:PACKAGE-SHADOW
           #:DOCUMENT
           #:PACKAGE-EXPORTED-SYMBOLS
           #:PACKAGE-SHADOWING-IMPORT-FROM
           #:PACKAGE-SYMBOLS
           #:INDEPENDENT-PACKAGES
           #:HIERARCHICAL-DEFPACKAGE-FORMS
           #:PACKAGE-IMPORT-FROMS
           #:PACKAGE-USED-SYMBOLS
           #:PACKAGE-EXTERNAL-SYMBOLS
           #:PACKAGE-IMPORTED-SYMBOLS
           #:PACKAGE?
           #:PACKAGE-EXTERNAL-SYMBOLS-FROM
           #:UNINTERNED
           #:PACKAGE-RE-EXPORT-SHADOWING
           #:PACKAGE-UNUSED-SYMBOLS
           #:PACKAGE-NON-SHADOWING-SYMBOLS
           #:DEFINE-PACKAGE
           #:PACKAGE-USE-SHADOWING
           #:EXTEND-PACKAGE*
           #:GROUP-BY-PACKAGE
           #:PACKAGE-EXPORT
           #:EXTEND-PACKAGE
           #:PACKAGE-IMPORT-FROM
           #:SYMBOLS-INTERNED-IN-PACKAGE
           #:PACKAGE-USE
           #:PACKAGE-FIND
           #:PACKAGE-SHADOWING-EXPORT))
(DEFPACKAGE #:SCHEMEISH.SCHEMEISH
  (:DOCUMENTATION "Provides everything in the schemeish-library. Re-exports CL so that packates can (:use #:schemeish) instead of (:use #:cl)")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:SORT #:STREAM #:MAP)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:COMMON-LISP
        #:SCHEMEISH.BASE
        #:SCHEMEISH.AND-LET
        #:SCHEMEISH.STREAM-COLLECT
        #:SCHEMEISH.BUNDLE
        #:SCHEMEISH.QUEUE
        #:SCHEMEISH.STRUCT
        #:SCHEMEISH.DEFINE-STRUCT
        #:SCHEMEISH.LEXICALLY
        #:SCHEMEISH.SERIALIZE)
  (:EXPORT #:LIST*
           #:LOGCOUNT
           #:DIRECTORY
           #:CDDAAR
           #:CHAR<=
           #:LOGIOR
           #:DO*
           #:VALUES-LIST
           #:STRING-NOT-EQUAL
           #:SYMBOL
           #:*LOAD-TRUENAME*
           #:SIMPLE-BASE-STRING
           #:WRITE-TO-STRING
           #:LEAST-NEGATIVE-SINGLE-FLOAT
           #:MAP-SUCCESSIVE
           #:MAP
           #:EVENP
           #:*PRINT-CASE*
           #:POSITIVE?
           #:STRING-RIGHT-TRIM
           #:SOME
           #:LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT
           #:STEP
           #:DOTIMES
           #:WRITE-BYTE
           #:INVALID-METHOD-ERROR
           #:BOOLE-NOR
           #:ROW-MAJOR-AREF
           #:USE-VALUE
           #:PARSE-INTEGER
           #:GRAPHIC-CHAR-P
           #:BLOCK
           #:DOLIST
           #:CONCATENATED-STREAM
           #:TRACE
           #:DOUBLE-FLOAT
           #:BROADCAST-STREAM-STREAMS
           #:CONSTANTLY
           #:SIMPLE-ARRAY
           #:DIGIT-CHAR-P
           #:SIMPLE-VECTOR-P
           #:STREAM-REF
           #:PACKAGE-ERROR
           #:BOOLE-ORC2
           #:CHAR>
           #:PACKAGE-USE-LIST
           #:STYLE-WARNING
           #:STREAM-FOLD
           #:/
           #:COUNT
           #:DISASSEMBLE
           #:NSET-DIFFERENCE
           #:DEFTYPE
           #:TREE-EQUAL
           #:*COMPILE-FILE-TRUENAME*
           #:SET-SUBTRACT
           #:RCURRY
           #:ADJUSTABLE-ARRAY-P
           #:HASH-TABLE-P
           #:WITH-OPEN-FILE
           #:AND
           #:HOST-NAMESTRING
           #:BUNDLE-DOCUMENTATION
           #:SUBSET?
           #:FBOUNDP
           #:SET-CAR!
           #:BIT-AND
           #:TYPE-ERROR-DATUM
           #:VECTOR
           #:STRING-STREAM
           #:SHADOWING-IMPORT
           #:STANDARD-CHAR-P
           #:*LOAD-PATHNAME*
           #:PRINT-UNREADABLE-OBJECT
           #:NINTH
           #:*PRINT-ESCAPE*
           #:FTRUNCATE
           #:MAKE-LIST
           #:FIND-IF-NOT
           #:MEMBER-IF-NOT
           #:INTERSECTION
           #:SATISFIES
           #:STRING-LESSP
           #:CHAR-NOT-EQUAL
           #:OUTPUT-STREAM-P
           #:WITH-OUTPUT-TO-STRING
           #:BOOLE-IOR
           #:EQ
           #:BREAK
           #:MOST-POSITIVE-DOUBLE-FLOAT
           #:CHAR-UPCASE
           #:NSTRING-CAPITALIZE
           #:CDR
           #:STANDARD-OBJECT
           #:STREAM-ELEMENT-TYPE
           #:STRING-APPEND
           #:LIST?
           #:STREAM-CONS
           #:PARSE-NAMESTRING
           #:MAKE-SYNONYM-STREAM
           #:WITH-COMPILATION-UNIT
           #:SET-MEMBER?
           #:REMOVE-METHOD
           #:ALIST-SET*
           #:MAPCAR
           #:CASE
           #:BOUNDP
           #:BOOLE-AND
           #:*PRINT-RADIX*
           #:+
           #:SCHAR
           #:LOWER-CASE-P
           #:READ-CHAR
           #:LIST-UPDATE
           #:NO-APPLICABLE-METHOD
           #:NUNION
           #:SET-EXCLUSIVE-OR
           #:NUMBER
           #:NTHCDR
           #:DEFINE-STRUCT
           #:SIMPLE-STRING-P
           #:SYNONYM-STREAM-SYMBOL
           #:MOST-POSITIVE-FIXNUM
           #:SIGNAL
           #:RASSOC
           #:COMPILED-FUNCTION
           #:LAMBDA
           #:ODDP
           #:UPPER-CASE-P
           #:*
           #:NSUBSTITUTE-IF-NOT
           #:NSUBLIS
           #:DEFINE-SETF-EXPANDER
           #:METHOD-COMBINATION
           #:WITH-SIMPLE-RESTART
           #:RPLACA
           #:ECASE
           #:NSET-EXCLUSIVE-OR
           #:ERROR
           #:PPRINT-POP
           #:STREAM-REST
           #:ASH
           #:FILE-ERROR
           #:CDDDAR
           #:FROUND
           #:BUILT-IN-CLASS
           #:CHAR-DOWNCASE
           #:LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT
           #:SUBSTITUTE-IF
           #:TRUNCATE
           #:BOOLE-C1
           #:SUBTYPEP
           #:MAKUNBOUND
           #:LOOP
           #:MULTIPLE-VALUE-LIST
           #:MAP-INTO
           #:IMPORT
           #:MERGE
           #:DEBUG
           #:GET-DISPATCH-MACRO-CHARACTER
           #:WRITE
           #:ZEROP
           #:STRUCT
           #:DISPLAYLN
           #:ALIST-SET
           #:LIST->STREAM
           #:LOGEQV
           #:DELETE-IF
           #:READ-LINE
           #:STREAM-EXTERNAL-FORMAT
           #:T
           #:FLOATING-POINT-OVERFLOW
           #:MOST-NEGATIVE-DOUBLE-FLOAT
           #:STREAM-RANGE
           #:REQUIRE
           #:RATIONALIZE
           #:GET
           #:STRUCT-FORM
           #:SLOT-BOUNDP
           #:LISTP
           #:MAPLIST
           #:*PRINT-LEVEL*
           #:NOR
           #:DEFCONSTANT
           #:FORCE-OUTPUT
           #:LONG-FLOAT
           #:INPUT-STREAM-P
           #:CDAAR
           #:LOGORC2
           #:STREAM
           #:&AUX
           #:PROVIDE
           #:PSETF
           #:APPEND
           #:ANDMAP
           #:MINUSP
           #:CHAR-INT
           #:COMPILE
           #:EVEN?
           #:FCEILING
           #:COMPILATION-SPEED
           #:DO-EXTERNAL-SYMBOLS
           #:INSPECT
           #:&BODY
           #:DELETE-DUPLICATES
           #:NTH
           #:LISTEN
           #:EQUAL?
           #:WRITE-STRING
           #:BOOLE-C2
           #:LOAD-TIME-VALUE
           #:CDADDR
           #:SEQUENCE
           #:COMPILE-FILE-PATHNAME
           #:GET-INTERNAL-REAL-TIME
           #:MAKE-BUNDLE-PREDICATE
           #:PACKAGE
           #:CLASS-NAME
           #:STREAM-APPEND
           #:ROUND
           #:BOOLE-XOR
           #:PHASE
           #:REAL
           #:STRING-LEFT-TRIM
           #:SOFTWARE-VERSION
           #:COPY-PPRINT-DISPATCH
           #:SLOT-MISSING
           #:NSUBST-IF-NOT
           #:CHAR-NAME
           #:STRING<=
           #:PPRINT-TABULAR
           #:SPECIAL
           #:ARITHMETIC-ERROR-OPERATION
           #:ENSURE-DIRECTORIES-EXIST
           #:UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
           #:&KEY
           #:SPECIAL-OPERATOR-P
           #:MAKE-CONDITION
           #:MAKE-KEYWORD
           #:&ENVIRONMENT
           #:SQR
           #:PSETQ
           #:UNBOUND-SLOT
           #:DOCUMENT!
           #:LOGICAL-PATHNAME
           #:BYTE
           #:FILTER
           #:WARNING
           #:NTH-VALUE
           #:WITH-ACCESSORS
           #:INTERNAL-TIME-UNITS-PER-SECOND
           #:WITH-STANDARD-IO-SYNTAX
           #:ARRAY-ELEMENT-TYPE
           #:EXPAND-TOP-LEVEL-DEFINE
           #:CLEAR-INPUT
           #:DOUBLE-FLOAT-EPSILON
           #:IMAGPART
           #:ARRAY-DISPLACEMENT
           #:COMPLEX
           #:SPLIT-AT
           #:PATHNAME-TYPE
           #:ATANH
           #:DECLARE
           #:SET-UNION
           #:FLOATP
           #:SINGLE-FLOAT-EPSILON
           #:READTABLEP
           #:STANDARD
           #:MEMBER-IF
           #:KEYWORDP
           #:TYPE
           #:PATHNAME-HOST
           #:LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT
           #:BIT-XOR
           #:-
           #:NINTERSECTION
           #:VECTOR-PUSH
           #:COSH
           #:CLEAR-OUTPUT
           #:STORE-VALUE
           #:GENERIC-FUNCTION
           #:PROCEDURE-ARITY
           #:COPY-SYMBOL
           #:FILE-STRING-LENGTH
           #:PATHNAME-VERSION
           #:DESTRUCTURING-BIND
           #:INTEGER-DECODE-FLOAT
           #:SIMPLE-CONDITION
           #:CHECK-TYPE
           #:STRING/=
           #:*PACKAGE*
           #:FORMAT
           #:NEGATIVE?
           #:EQ?
           #:ALIST-MAP
           #:READ-SEQUENCE
           #:MOST-POSITIVE-SHORT-FLOAT
           #:SIMPLE-VECTOR
           #:FIND-METHOD
           #:MERGE-PATHNAMES
           #:TAN
           #:ZERO?
           #:*FEATURES*
           #:ARITHMETIC-ERROR-OPERANDS
           #:LOGAND
           #:DIGIT-CHAR
           #:SIMPLE-WARNING
           #:*MODULES*
           #:FUNCTION
           #:FFLOOR
           #:LIST-TAIL
           #:PPRINT-EXIT-IF-LIST-EXHAUSTED
           #:Y-OR-N-P
           #:LEXICALLY
           #:SUBST-IF
           #:MACROLET
           #:*PRINT-CIRCLE*
           #:DOUBLE-FLOAT-NEGATIVE-EPSILON
           #:STREAM-TAKE
           #:WITH-SLOTS
           #:COMPILER-MACRO
           #:STRING-UPCASE
           #:CAAR
           #:PARTITION
           #:TENTH
           #:NSUBSTITUTE-IF
           #:*PRINT-RIGHT-MARGIN*
           #:REALPART
           #:REMOVE*
           #:PROCEDURE-ARGUMENTS
           #:STABLE-SORT
           #:OPTIMIZE
           #:MAKE-HASH-TABLE
           #:REMOVE-IF
           #:CHAR-NOT-GREATERP
           #:INVOKE-RESTART-INTERACTIVELY
           #:ASSOC-IF-NOT
           #:CONSP
           #:INSTALL-SYNTAX!
           #:SEVENTH
           #:SYMBOL-PACKAGE
           #:LIST-ALL-PACKAGES
           #:*PRINT-BASE*
           #:SORT
           #:MASK-FIELD
           #:UNSIGNED-BYTE
           #:FOLDR
           #:EXPAND-FUNCTION-BODY
           #:COND
           #:LOGNAND
           #:DIVISION-BY-ZERO
           #:NULL
           #:LEAST-NEGATIVE-DOUBLE-FLOAT
           #:LEAST-POSITIVE-DOUBLE-FLOAT
           #:REMQ*
           #:ALIST
           #:1+
           #:NBUTLAST
           #:METHOD-QUALIFIERS
           #:SECOND
           #:PROCEDURE-ARGUMENTS-REST-ARGUMENT
           #:SET=?
           #:DOCUMENTATION
           #:RESTART
           #:BIT-IOR
           #:SUBST
           #:STREAM?
           #:SPEED
           #:FOR-EACH
           #:SET-SYNTAX-FROM-CHAR
           #:UNDEFINED-FUNCTION
           #:MACRO-FUNCTION
           #:DIRECTORY-NAMESTRING
           #:EMPTY?
           #:DEFMETHOD
           #:METHOD-COMBINATION-ERROR
           #:EIGHTH
           #:BOOLE-EQV
           #:RESTART-CASE
           #:EXTENDED-CHAR
           #:SET-COUNT
           #:PATHNAME-DEVICE
           #:OPEN-STREAM-P
           #:COUNT-IF-NOT
           #:NEWLINE
           #:MAPL
           #:EQUALP
           #:FIND
           #:CHAR-CODE
           #:MULTIPLE-VALUE-SETQ
           #:QUEUE-INSERT!
           #:MAKE-PATHNAME
           #:IDENTITY
           #:SLEEP
           #:CODE-CHAR
           #:EXPT
           #:NUMBER->STRING
           #:SYMBOL->STRING
           #:STRUCT->LIST
           #:COPY-LIST
           #:RESTART-NAME
           #:PPRINT-LOGICAL-BLOCK
           #:*GENSYM-COUNTER*
           #:RENAME-PACKAGE
           #:UNWIND-PROTECT
           #:RASSOC-IF
           #:POP
           #:ENCODE-UNIVERSAL-TIME
           #:STREAM-FILTER
           #:NCONC
           #:MULTIPLE-VALUE-BIND
           #:PROG*
           #:BOOLE
           #:MOST-POSITIVE-SINGLE-FLOAT
           #:STRING<
           #:USE-PACKAGE
           #:*MACROEXPAND-HOOK*
           #:DPB
           #:CELL-ERROR
           #:STREAM-FLATMAP
           #:MAKE-STRING
           #:LIST-REF
           #:ROTATEF
           #:WITH-OPEN-STREAM
           #:RATIONALP
           #:NOTANY
           #:DECLAIM
           #:ALIST-HAS-KEY?
           #:FILE-STREAM
           #:BOOLE-SET
           #:MOST-POSITIVE-LONG-FLOAT
           #:GCD
           #:FDEFINITION
           #:*PRINT-PPRINT-DISPATCH*
           #:FILE-POSITION
           #:STREAM-DROP
           #:SIMPLE-TYPE-ERROR
           #:FLOAT
           #:OTHERWISE
           #:FIXNUM
           #:SINGLE-FLOAT
           #:BUNDLE
           #:COMPUTE-APPLICABLE-METHODS
           #:PRINT
           #:MAKE-LOAD-FORM
           #:TRUENAME
           #:VARIABLE
           #:*COMPILE-VERBOSE*
           #:IGNORE-ERRORS
           #:UNEXPORT
           #:VECTOR-POP
           #:CTYPECASE
           #:ASSERT
           #:REPLACE
           #:*QUERY-IO*
           #:STREAM-CAR
           #:SXHASH
           #:CADDAR
           #:MAKE-SEQUENCE
           #:FUNCTION-KEYWORDS
           #:SHADOW
           #:DENOMINATOR
           #:CHAR>=
           #:PI
           #:ARRAY-DIMENSION-LIMIT
           #:ISQRT
           #:TWO-WAY-STREAM-INPUT-STREAM
           #:SIMPLE-BIT-VECTOR
           #:LOGNOR
           #:MACHINE-VERSION
           #:SCALE-FLOAT
           #:LDB
           #:DECODE-UNIVERSAL-TIME
           #:LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT
           #:PRINT-NOT-READABLE
           #:*PRINT-ARRAY*
           #:LIST-LENGTH
           #:CDAADR
           #:COMPUTE-RESTARTS
           #:CONJUGATE
           #:INVOKE-DEBUGGER
           #:GET-DECODED-TIME
           #:ASINH
           #:PACKAGE-NAME
           #:1-
           #:DO-ALL-SYMBOLS
           #:LISP-IMPLEMENTATION-TYPE
           #:LEAST-NEGATIVE-SHORT-FLOAT
           #:CONS
           #:QUEUE?
           #:LOGXOR
           #:REMHASH
           #:MAKE-LOAD-FORM-SAVING-SLOTS
           #:ROOM
           #:SUBST-IF-NOT
           #:PACKAGE-NICKNAMES
           #:ED
           #:MAKE-CONCATENATED-STREAM
           #:MOST-NEGATIVE-SHORT-FLOAT
           #:*READTABLE*
           #:STREAM-ERROR-STREAM
           #:SERIOUS-CONDITION
           #:SHORT-SITE-NAME
           #:CDDR
           #:MACROEXPAND-1
           #:SHORT-FLOAT
           #:NSUBST-IF
           #:FILTER-NOT
           #:MAKE-QUEUE
           #:EXPOSE
           #:MULTIPLE-VALUE-CALL
           #:LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT
           #:DEFINE
           #:REMOVE-IF-NOT
           #:BROADCAST-STREAM
           #:CONCATENATED-STREAM-STREAMS
           #:LOAD
           #:REALP
           #:PPRINT
           #:REST
           #:REMOVE
           #:DISPLAY
           #:COPY-TREE
           #:ARITHMETIC-ERROR
           #:ACOSH
           #:BASE-STRING
           #:BYTE-POSITION
           #:FIRST
           #:UNUSE-PACKAGE
           #:STRUCTURE-CLASS
           #:CELL-ERROR-NAME
           #:ORMAP
           #:NO-NEXT-METHOD
           #:GENTEMP
           #:ARRAY-RANK-LIMIT
           #:&OPTIONAL
           #:NUMERATOR
           #:IN-PACKAGE
           #:ASIN
           #:BOTH-CASE-P
           #:HANDLER-BIND
           #:*PRINT-PRETTY*
           #:CADR
           #:STRING
           #:*THE-EMPTY-STREAM*
           #:STANDARD-GENERIC-FUNCTION
           #:FILE-WRITE-DATE
           #:CADAR
           #:WRITE-SEQUENCE
           #:SIN
           #:LET
           #:AND-LET*
           #:DESCRIBE-OBJECT
           #:APPEND-MAP
           #:CADDDR
           #:ELT
           #:FLOAT-PRECISION
           #:ARRAY-RANK
           #:NAND
           #:ALLOCATE-INSTANCE
           #:LAST
           #:NSUBSTITUTE
           #:HASH-TABLE-REHASH-SIZE
           #:MAKE-ARRAY
           #:BOOLE-ORC1
           #:TAILP
           #:CONCATENATE
           #:INLINE
           #:PROCEDURE-ARGUMENTS-KEY-ARGUMENTS
           #:NAMESTRING
           #:INTERN
           #:PRINC-TO-STRING
           #:STRINGP
           #:STRING>
           #:EVERY
           #:TYPECASE
           #:DYNAMIC-EXTENT
           #:WRITE-LINE
           #:FIFTH
           #:LEAST-POSITIVE-SINGLE-FLOAT
           #:MULTIPLE-VALUES-LIMIT
           #:NOTINLINE
           #:SVREF
           #:PPRINT-INDENT
           #:INTEGERP
           #:MAX
           #:TRANSLATE-LOGICAL-PATHNAME
           #:TYPEP
           #:OR
           #:COPY-SEQ
           #:CDADAR
           #:*BREAK-ON-SIGNALS*
           #:BUTLAST
           #:PACKAGE-USED-BY-LIST
           #:ACONS
           #:INTEGER
           #:DO-SYMBOLS
           #:/=
           #:PPRINT-NEWLINE
           #:PROCLAIM
           #:CATCH
           #:RETURN
           #:MISMATCH
           #:STRUCTURE
           #:GET-PROPERTIES
           #:SET-CDR!
           #:CADAAR
           #:BIT
           #:ADJUST-ARRAY
           #:UNLESS
           #:CDAR
           #:BUNDLE-PERMISSIONS
           #:FIND-RESTART
           #:FILL
           #:SUBSETP
           #:VECTORP
           #:SET-EMPTY?
           #:SWAP-ARGS
           #:TWO-WAY-STREAM-OUTPUT-STREAM
           #:PATHNAME-NAME
           #:FILE-LENGTH
           #:LAMBDA-PARAMETERS-LIMIT
           #:MAKE-INSTANCES-OBSOLETE
           #:WITH-INPUT-FROM-STRING
           #:STRING=
           #:LENGTH
           #:SET-MACRO-CHARACTER
           #:READ-BYTE
           #:PACKAGEP
           #:POSITION-IF-NOT
           #:MAPC
           #:ALIST-VALUES
           #:WARN
           #:CAAAR
           #:LEAST-POSITIVE-LONG-FLOAT
           #:METHOD
           #:FILE-ERROR-PATHNAME
           #:CHARACTER
           #:>=
           #:QUEUE-EMPTY?
           #:WRITE-CHAR
           #:FILTER-MAP
           #:RATIONAL
           #:MAKE-DISPATCH-MACRO-CHARACTER
           #:ATAN
           #:PACKAGE-SHADOWING-SYMBOLS
           #:DEFMACRO
           #:SET-REMOVE
           #:HASH-TABLE-SIZE
           #:DROP
           #:FILE-AUTHOR
           #:QUEUE-DELETE!
           #:DEFGENERIC
           #:DELETE-PACKAGE
           #:ADD-METHOD
           #:LOOP-FINISH
           #:RANDOM
           #:TAKE
           #:RATIO
           #:BIT-NAND
           #:OPEN
           #:DEFCLASS
           #:MUFFLE-WARNING
           #:PRINT-OBJECT
           #:NOT
           #:DO
           #:CDDDR
           #:SIMPLE-ERROR
           #:*DEFAULT-PATHNAME-DEFAULTS*
           #:SIGNUM
           #:POSITION
           #:DEFSTRUCT
           #:NRECONC
           #:UPDATE-INSTANCE-FOR-REDEFINED-CLASS
           #:USER-HOMEDIR-PATHNAME
           #:STREAMP
           #:DEPOSIT-FIELD
           #:GROUP
           #:STRING-DOWNCASE
           #:FLOATING-POINT-INEXACT
           #:ALIST-REMOVE
           #:TYPE-ERROR
           #:LEAST-NEGATIVE-LONG-FLOAT
           #:UNBOUND-SLOT-INSTANCE
           #:GET-OUTPUT-STREAM-STRING
           #:LABELS
           #:READ-DELIMITED-LIST
           #:CONST
           #:*LOAD-PRINT*
           #:CONJOIN*
           #:WHEN
           #:DELETE-IF-NOT
           #:SHORT-FLOAT-NEGATIVE-EPSILON
           #:ABORT
           #:MAKE-STRING-OUTPUT-STREAM
           #:MAKE-PACKAGE
           #:FLOAT-DIGITS
           #:EXP
           #:LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT
           #:COMPOSE
           #:CAAAAR
           #:DELAY
           #:DECODE-FLOAT
           #:QUEUE-FRONT
           #:RANDOM-STREAM
           #:CONTROL-ERROR
           #:SYMBOL-NAME
           #:ARRAY-DIMENSIONS
           #:BOOLE-2
           #:LOAD-LOGICAL-PATHNAME-TRANSLATIONS
           #:INTERACTIVE-STREAM-P
           #:ECHO-STREAM-INPUT-STREAM
           #:ASSOC
           #:DEFINE-COMPILER-MACRO
           #:CHANGE-CLASS
           #:CDDAR
           #:MAKE-BROADCAST-STREAM
           #:MAPCAN
           #:FMAKUNBOUND
           #:ARRAY-TOTAL-SIZE
           #:ALIST-REF
           #:ENDP
           #:STREAM-CDR
           #:COPY-ALIST
           #:*ERROR-OUTPUT*
           #:NSTRING-DOWNCASE
           #:STRING-TRIM
           #:SET-DIFFERENCE
           #:EVAL
           #:CHAR-GREATERP
           #:MACHINE-TYPE
           #:ACOS
           #:THROW
           #:EVAL-WHEN
           #:PARSE-ERROR
           #:MEMO-PROC
           #:PUSHNEW
           #:*COMPILE-FILE-PATHNAME*
           #:ARRAY-DIMENSION
           #:*PRINT-MISER-WIDTH*
           #:REMPROP
           #:MAKE-INSTANCE
           #:FLOOR
           #:PRINT-NOT-READABLE-OBJECT
           #:NUMBER?
           #:BOOLE-1
           #:QUOTE
           #:BIT-EQV
           #:POSITION-IF
           #:UPGRADED-COMPLEX-PART-TYPE
           #:*TERMINAL-IO*
           #:SUBSEQ
           #:STREAM-EMPTY?
           #:STREAM-LENGTH
           #:FOURTH
           #:CONTINUE
           #:CDDDDR
           #:MIN
           #:SYMBOL-VALUE
           #:CERROR
           #:CADADR
           #:BOOLE-NAND
           #:CIS
           #:IF
           #:RPLACD
           #:APPEND*
           #:WITH-HASH-TABLE-ITERATOR
           #:INCF
           #:RASSOC-IF-NOT
           #:PROGV
           #:GETF
           #:GET-SETF-EXPANSION
           #:GET-UNIVERSAL-TIME
           #:BIGNUM
           #:BUNDLE-LIST
           #:TWO-WAY-STREAM
           #:SHIFTF
           #:AREF
           #:FUNCALL
           #:UPGRADED-ARRAY-ELEMENT-TYPE
           #:UNREAD-CHAR
           #:PPRINT-FILL
           #:THERE-EXISTS
           #:&WHOLE
           #:HASH-TABLE-REHASH-THRESHOLD
           #:CAAADR
           #:MEMBER
           #:FOLDL
           #:PRIN1-TO-STRING
           #:MACHINE-INSTANCE
           #:READTABLE
           #:PROBE-FILE
           #:MAKE-TWO-WAY-STREAM
           #:REMOVE-DUPLICATES
           #:NSUBST
           #:=
           #:STREAM-ERROR
           #:GENSYM
           #:PRINC
           #:SINGLE-FLOAT-NEGATIVE-EPSILON
           #:CALL-NEXT-METHOD
           #:RADIANS->DEGREES
           #:CONSTANTP
           #:THERE-EXISTS*
           #:PROG
           #:WITH-CONDITION-RESTARTS
           #:*PRINT-LINES*
           #:SIMPLE-STRING
           #:FTYPE
           #:CONJOIN
           #:LOGBITP
           #:FUNCTIONP
           #:ALIST-UPDATE
           #:FILE-NAMESTRING
           #:FRESH-LINE
           #:CLOSE
           #:PATHNAME-DIRECTORY
           #:LEAST-POSITIVE-SHORT-FLOAT
           #:PROCEDURE-ARGUMENTS-ALLOW-OTHER-KEYS?
           #:<
           #:STRING-GREATERP
           #:GET-MACRO-CHARACTER
           #:TYPE-OF
           #:MEMF
           #:DECF
           #:PROG1
           #:COMPILER-MACRO-FUNCTION
           #:SIMPLE-CONDITION-FORMAT-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-OPTIONAL-ARGUMENTS
           #:UNINTERN
           #:COUNT-IF
           #:CAADDR
           #:SET
           #:FORCE
           #:READER-ERROR
           #:LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT
           #:SHORT-FLOAT-EPSILON
           #:CHAR-EQUAL
           #:READ
           #:SLOT-MAKUNBOUND
           #:LEAST-POSITIVE-NORMALIZED-LONG-FLOAT
           #:LOGANDC1
           #:COPY-READTABLE
           #:EQL
           #:*TRACE-OUTPUT*
           #:DISJOIN
           #:&ALLOW-OTHER-KEYS
           #:FIND-IF
           #:YES-OR-NO-P
           #:FORMATTER
           #:>
           #:IGNORABLE
           #:MOST-NEGATIVE-SINGLE-FLOAT
           #:SIXTH
           #:SIMPLE-CONDITION-FORMAT-CONTROL
           #:IGNORE
           #:SLOT-EXISTS-P
           #:FIND-SYMBOL
           #:DEFUN
           #:DEFINE-SYMBOL-MACRO
           #:LAMBDA-LIST-KEYWORDS
           #:STREAM-FOR-EACH
           #:SHARED-INITIALIZE
           #:PPRINT-DISPATCH
           #:*READ-EVAL*
           #:STREAM-MAP
           #:CCASE
           #:*PRINT-GENSYM*
           #:*READ-SUPPRESS*
           #:RENAME-FILE
           #:WITH-PACKAGE-ITERATOR
           #:APPLY
           #:CHAR-CODE-LIMIT
           #:INITIALIZE-INSTANCE
           #:STREAM-FLATTEN
           #:STRUCT-COPY
           #:CHAR-LESSP
           #:*PRINT-LENGTH*
           #:COMPILED-FUNCTION-P
           #:SYMBOLP
           #:HAS-SPECIFIC-ARITY?
           #:VECTOR-PUSH-EXTEND
           #:STRING?
           #:TAGBODY
           #:REM
           #:PATHNAMEP
           #:ENSURE-GENERIC-FUNCTION
           #:SETQ
           #:PPRINT-TAB
           #:LOGNOT
           #:MOD
           #:SUBSTITUTE
           #:BIT-ANDC1
           #:FIND-ALL-SYMBOLS
           #:CALL-METHOD
           #:SUBLIS
           #:TERPRI
           #:SETF
           #:UNINSTALL-SYNTAX!
           #:SAFETY
           #:*LOAD-VERBOSE*
           #:PACKAGE-ERROR-PACKAGE
           #:GET-INTERNAL-RUN-TIME
           #:SET-DISPATCH-MACRO-CHARACTER
           #:SYMBOL?
           #:SET-INTERSECT
           #:STANDARD-CLASS
           #:PROCEDURE?
           #:SET!
           #:QUOTIENT
           #:ARRAY-HAS-FILL-POINTER-P
           #:STORAGE-CONDITION
           #:PROGN
           #:LOGORC1
           #:FIND-CLASS
           #:LCM
           #:HASH-TABLE-TEST
           #:ARRAY-IN-BOUNDS-P
           #:MAKE-SYMBOL
           #:CADDR
           #:COMPLEMENT
           #:PATHNAME-MATCH-P
           #:STREAM->LIST
           #:BUNDLE?
           #:ETYPECASE
           #:LONG-SITE-NAME
           #:<=
           #:DEFSETF
           #:CHAR/=
           #:SIGNED-BYTE
           #:NEXT-METHOD-P
           #:CHARACTERP
           #:PEEK-CHAR
           #:STRING-NOT-LESSP
           #:LISP-IMPLEMENTATION-VERSION
           #:ARRAY-ROW-MAJOR-INDEX
           #:STRUCT?
           #:DESCRIBE
           #:NOTEVERY
           #:SINH
           #:*READ-BASE*
           #:XOR
           #:BASE-CHAR
           #:NIL
           #:BIT-NOT
           #:INTEGER-LENGTH
           #:ALIST-KEYS
           #:FIND-PACKAGE
           #:STREAM-FIRST
           #:ARRAY-TOTAL-SIZE-LIMIT
           #:STRING-CAPITALIZE
           #:SLOT-UNBOUND
           #:MAPHASH
           #:ALPHANUMERICP
           #:SBIT
           #:BOOLEAN
           #:SLOT-VALUE
           #:*RANDOM-STATE*
           #:LCURRY
           #:LOG
           #:STANDARD-CHAR
           #:PPRINT-LINEAR
           #:BIT-VECTOR
           #:CHAR-NOT-LESSP
           #:ENOUGH-NAMESTRING
           #:SET-PPRINT-DISPATCH
           #:PROGRAM-ERROR
           #:LIST-SET
           #:PAIRLIS
           #:UNION
           #:MOST-NEGATIVE-FIXNUM
           #:CDAAAR
           #:BIT-ANDC2
           #:&REST
           #:FINDF
           #:GETHASH
           #:ATOM
           #:DEFINE-METHOD-COMBINATION
           #:TIME
           #:BIT-NOR
           #:ECHO-STREAM
           #:EQUAL
           #:READ-FROM-STRING
           #:FUNCTION-LAMBDA-EXPRESSION
           #:ODD?
           #:FOR-MACROS
           #:READ-CHAR-NO-HANG
           #:MOST-NEGATIVE-LONG-FLOAT
           #:FINISH-OUTPUT
           #:FLOAT-SIGN
           #:*READ-DEFAULT-FLOAT-FORMAT*
           #:WILD-PATHNAME-P
           #:STANDARD-METHOD
           #:STRING>=
           #:ECHO-STREAM-OUTPUT-STREAM
           #:UNBOUND-VARIABLE
           #:TYPE-ERROR-EXPECTED-TYPE
           #:LOGANDC2
           #:SEARCH
           #:APROPOS
           #:COPY-STRUCTURE
           #:THE
           #:DEFINE-MODIFY-MACRO
           #:RANDOM-STATE
           #:*DEBUG-IO*
           #:CAADR
           #:CLRHASH
           #:BOOLE-ANDC1
           #:SOFTWARE-TYPE
           #:DEFVAR
           #:CLASS
           #:*STANDARD-INPUT*
           #:SPACE
           #:MACROEXPAND
           #:DELETE
           #:MAPCON
           #:CEILING
           #:DEFPACKAGE
           #:REMQ
           #:LONG-FLOAT-NEGATIVE-EPSILON
           #:CHAR=
           #:LOGTEST
           #:DEFINE-CONDITION
           #:BOOLE-ANDC2
           #:KEYWORD
           #:FLATTEN
           #:DELETE-FILE
           #:COMPLEXP
           #:REVERSE
           #:PUSH
           #:NREVERSE
           #:STRING-EQUAL
           #:MAKE-METHOD
           #:LONG-FLOAT-EPSILON
           #:PAIR?
           #:REDUCE
           #:CHAR
           #:DEFPARAMETER
           #:PATHNAME
           #:END-OF-FILE
           #:HANDLER-CASE
           #:CAADAR
           #:CONDITION
           #:RESTART-BIND
           #:REMF
           #:STRING-STARTS-WITH?
           #:PROG2
           #:BIT-VECTOR-P
           #:NULL?
           #:LOGICAL-PATHNAME-TRANSLATIONS
           #:*STANDARD-OUTPUT*
           #:FLOATING-POINT-INVALID-OPERATION
           #:MAKE-ECHO-STREAM
           #:ALPHA-CHAR-P
           #:BYTE-SIZE
           #:FLOATING-POINT-UNDERFLOW
           #:APROPOS-LIST
           #:SGN
           #:INVOKE-RESTART
           #:READ-PRESERVING-WHITESPACE
           #:TANH
           #:MAKE-RANDOM-STATE
           #:UNTRACE
           #:RANGE
           #:SET-ADD
           #:COMPILE-FILE
           #:CLASS-OF
           #:BIT-ORC1
           #:FLET
           #:HASH-TABLE-COUNT
           #:NAME-CHAR
           #:SYMBOL-PLIST
           #:SYNONYM-STREAM
           #:RETURN-FROM
           #:STRING-NOT-GREATERP
           #:NUMBERP
           #:LDB-TEST
           #:*PRINT-READABLY*
           #:ABS
           #:MULTIPLE-VALUE-PROG1
           #:STREAM-MAP-SUCCESSIVE
           #:CHAR<
           #:DECLARATION
           #:COERCE
           #:RANDOM-STATE-P
           #:PRIN1
           #:STREAM-COLLECT
           #:NSTRING-UPCASE
           #:HASH-TABLE
           #:ARRAY
           #:DRIBBLE
           #:SYMBOL-FUNCTION
           #:FOR-ALL*
           #:COS
           #:GO
           #:FILL-POINTER
           #:CDADR
           #:*COMPILE-PRINT*
           #:EXPORT
           #:ADJOIN
           #:BIT-ORC2
           #:LIST
           #:STRUCT-ACCESSORS
           #:ASSOC-IF
           #:PROCEDURE-ARGUMENTS-REQUIRED-ARGUMENTS
           #:DEGREES->RADIANS
           #:DISJOIN*
           #:LET*
           #:THIRD
           #:CALL-ARGUMENTS-LIMIT
           #:STRUCTURE-OBJECT
           #:ARRAYP
           #:REVAPPEND
           #:LOCALLY
           #:LDIFF
           #:SIMPLE-BIT-VECTOR-P
           #:CDDADR
           #:SQRT
           #:SERIALIZE
           #:SYMBOL-MACROLET
           #:READTABLE-CASE
           #:PLUSP
           #:*DEBUGGER-HOOK*
           #:FOR-ALL
           #:REINITIALIZE-INSTANCE
           #:TRANSLATE-PATHNAME
           #:FLOAT-RADIX
           #:VALUES
           #:BOOLE-CLR
           #:CAR
           #:SUBSTITUTE-IF-NOT
           #:SET->STREAM
           #:MAKE-STRING-INPUT-STREAM)
  (:SHADOW #:++ #:+++ #:// #:/// #:** #:*** #:+ #:/ #:* #:-))
(DEFPACKAGE #:SCHEMEISH.PACKAGE-DEFINITIONS
  (:DOCUMENTATION "Source of all of the package definitions in SCHEMEISH.
Provides write-package-file! which writes the current schemeish-packages to a file.")
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.SCHEMEISH
                          #://
                          #:///
                          #:+++
                          #:***
                          #:++
                          #:*
                          #:+
                          #:**
                          #:-
                          #:/)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BASE #:MAP #:STREAM #:SORT)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.DEFINE #:LAMBDA)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.NAMED-LET #:LET)
  (:USE #:SCHEMEISH.PACKAGE-UTILS #:SCHEMEISH.SCHEMEISH)
  (:EXPORT #:SCHEMEISH-PACKAGES #:WRITE-PACKAGE-FILE!))
