(DEFPACKAGE #:SCHEMEISH.INTERNALS
  (:USE #:COMMON-LISP)
  (:EXPORT #:COMPILER-MACRO-DOCUMENTATION-SOURCE
           #:DISABLE-GUARD-CLAUSES!
           #:DOCUMENTATION-SOURCE?
           #:DOCUMENTATION-STRING
           #:DOCUMENTATION-TAG
           #:DOCUMENTATION-TAG-FORM
           #:DOCUMENTATION-TAG?
           #:ENABLE-GUARD-CLAUSES!
           #:GUARD-CLAUSES-ENABLED?
           #:GUARD-TAG
           #:GUARD-TAG-CLAUSES
           #:GUARD-TAG?
           #:MAKE-DOCUMENTATION-TAG
           #:MAKE-GUARD-TAG
           #:OBJECT-DOCUMENTATION-SOURCE
           #:READ-GUARD-TAG
           #:REGISTERED-GUARD-CLAUSES
           #:SCM-PARAMETERS->ORDINARY-LAMBDA-LIST
           #:SET-COMPILER-MACRO-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-FROM-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-SOURCE!
           #:SET-SETF-DOCUMENTATION-SOURCE!
           #:SET-TYPE-DOCUMENTATION-SOURCE!
           #:SET-VARIABLE-DOCUMENTATION-SOURCE!
           #:SETF-DOCUMENTATION-SOURCE
           #:TYPE-DOCUMENTATION-SOURCE
           #:UNIQUE-SYMBOL
           #:VARIABLE-DOCUMENTATION-SOURCE
           #:WITH-GUARD-CLAUSES-DISABLED
           #:WITH-GUARD-CLAUSES-ENABLED
           #:WITH-READABLE-SYMBOLS))
