(DEFPACKAGE #:SCHEMEISH.INTERNALS
  (:USE #:COMMON-LISP)
  (:EXPORT #:COMPILER-MACRO-DOCUMENTATION-SOURCE
           #:DEFINE
           #:DISABLE-GUARD-CLAUSES!
           #:DOCUMENTATION-SOURCE?
           #:DOCUMENTATION-STRING
           #:DOCUMENTATION-TAG
           #:DOCUMENTATION-TAG-FORM
           #:DOCUMENTATION-TAG?
           #:DROPF
           #:ENABLE-GUARD-CLAUSES!
           #:EXPOSE
           #:EXPOSE-FUNCTIONS
           #:EXPOSE-VARIABLES
           #:FOR-MACROS
           #:GUARD-CLAUSES-ENABLED?
           #:GUARD-TAG
           #:GUARD-TAG-CLAUSES
           #:GUARD-TAG?
           #:INSTALL-SYNTAX!
           #:LAMBDA-FORM
           #:LET
           #:LEXICAL-BODY-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY-DEFINITION?
           #:LEXICAL-BODY-FORM
           #:LEXICAL-BODY2-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY2-DEFINITION?
           #:LEXICAL-BODY2-FORM
           #:LEXICALLY
           #:MAKE-DOCUMENTATION-TAG
           #:MAKE-GUARD-TAG
           #:NO-COMPILE
           #:OBJECT-DOCUMENTATION-SOURCE
           #:PARSE-FUNCTION
           #:PARSE-METADATA-FROM-FUNCTION-BODY
           #:READ-GUARD-TAG
           #:REGISTER-LEXICAL-BODY-DEFINITION
           #:REGISTER-LEXICAL-BODY2-DEFINITION
           #:REGISTERED-DEFINITION-NAME-FIELD
           #:REGISTERED-GUARD-CLAUSES
           #:SCM-PARAMETERS->ORDINARY-LAMBDA-LIST
           #:SET-COMPILER-MACRO-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-FROM-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-SOURCE!
           #:SET-SETF-DOCUMENTATION-SOURCE!
           #:SET-TYPE-DOCUMENTATION-SOURCE!
           #:SET-VARIABLE-DOCUMENTATION-SOURCE!
           #:SETF-DOCUMENTATION-SOURCE
           #:SPLITF
           #:TAKEF
           #:TRANSFORM-LEXICAL-BODY-DEFINE-DESTRUCTURING
           #:TRANSFORM-LEXICAL-BODY-DEFINE-SYMBOL-OR-PAIR
           #:TRANSFORM-LEXICAL-BODY-DEFINE-VALUES
           #:TRANSFORM-LEXICAL-BODY2-DEFINE-SYMBOL-OR-PAIR
           #:TYPE-DOCUMENTATION-SOURCE
           #:UNDEFINE
           #:UNINSTALL-SYNTAX!
           #:UNIQUE-SYMBOL
           #:UNREGISTER-LEXICAL-BODY-DEFINITION
           #:UNREGISTER-LEXICAL-BODY2-DEFINITION
           #:VARIABLE-DOCUMENTATION-SOURCE
           #:WITH-GUARD-CLAUSES-DISABLED
           #:WITH-GUARD-CLAUSES-ENABLED
           #:WITH-READABLE-SYMBOLS)
  (:SHADOW #:LET))

(DEFPACKAGE #:SCHEMEISH.BACKEND
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.INTERNALS #:LET)
  (:USE #:COMMON-LISP #:SCHEMEISH.INTERNALS)
  (:EXPORT #:*ESCAPE-CHARS*
           #:*MARKUP-RENDER-WIDTH*
           #:*THE-EMPTY-STREAM*
           #:ALIST
           #:ALIST-FOR-EACH
           #:ALIST-HAS-KEY?
           #:ALIST-KEYS
           #:ALIST-MAP
           #:ALIST-REF
           #:ALIST-REMOVE
           #:ALIST-SET
           #:ALIST-SET*
           #:ALIST-UNION
           #:ALIST-UPDATE
           #:ALIST-VALUES
           #:AND-LET*
           #:ANDMAP
           #:APPEND*
           #:APPEND-MAP
           #:BLOCK-QUOTE
           #:BOLD
           #:BR
           #:BUNDLE
           #:BUNDLE-DOCUMENTATION
           #:BUNDLE-PERMISSIONS
           #:BUNDLE?
           #:CHARS-STRING
           #:CODE
           #:CODE-BLOCK
           #:COMPOSE
           #:COMPOSE*
           #:CONJOIN
           #:CONJOIN*
           #:CONST
           #:COPY-RENDERER-WITH-NEW-STREAM
           #:DEFINE-BUNDLE-PRINT-OBJECT
           #:DEFINE-STRUCT
           #:DEGREES->RADIANS
           #:DELAY
           #:DISJOIN
           #:DISJOIN*
           #:DISPLAY
           #:DISPLAYLN
           #:DROP
           #:EMPTY?
           #:EQ?
           #:EQUAL?
           #:EVEN?
           #:FILTER
           #:FILTER-MAP
           #:FILTER-NOT
           #:FINDF
           #:FLATTEN
           #:FOLDL
           #:FOLDR
           #:FOR-ALL
           #:FOR-ALL*
           #:FOR-EACH
           #:FORCE
           #:GROUP
           #:HAS-SPECIFIC-ARITY?
           #:HASH->ALIST
           #:HASH-CLEAR!
           #:HASH-FIND-KEYF
           #:HASH-FOR-EACH
           #:HASH-KEYS
           #:HASH-MAP
           #:HASH-REF
           #:HASH-REF-DEFAULT
           #:HASH-REMOVE!
           #:HASH-SET!
           #:HASH-UPDATE!
           #:HASH-VALUES
           #:HEADING
           #:HORIZONTAL-BAR
           #:HTML-TAG
           #:HTML-TAG-ATTRIBUTE-ALIST
           #:HTML-TAG-INNER-TAGS-AND-TEXTS
           #:HTML-TAG-NAME
           #:HTML-TAG?
           #:IGNORE-ARGS
           #:INLINE-MARKUP
           #:INLINE-MARKUP?
           #:INLINE-TEXT
           #:INLINE-TEXT?
           #:INTERSPERSE
           #:ITALIC
           #:JOIN-STRINGS
           #:LAMBDA
           #:LCURRY
           #:LETREC
           #:LINK
           #:LIST->STREAM
           #:LIST->STRING
           #:LIST->VECTOR
           #:LIST-ITEM-TAG
           #:LIST-REF
           #:LIST-SET
           #:LIST-TAIL
           #:LIST-TYPE
           #:LIST-UPDATE
           #:LIST?
           #:MAKE-BUNDLE-PREDICATE
           #:MAKE-HTML-TAG
           #:MAKE-INLINE-MARKUP
           #:MAKE-KEYWORD
           #:MAKE-MARKUP
           #:MAKE-QUEUE
           #:MAP
           #:MAP-SUCCESSIVE
           #:MARKUP
           #:MARKUP-CONSTRUCTOR
           #:MARKUP-CONSTRUCTOR-FORM
           #:MARKUP-HTML-TAG
           #:MARKUP-RENDER-TEXT
           #:MARKUP-STRING-RENDERER
           #:MARKUP?
           #:MEMF
           #:MEMO-PROC
           #:NAND
           #:NEGATIVE?
           #:NEWLINE
           #:NOR
           #:NULL?
           #:NUMBER->STRING
           #:NUMBER?
           #:ODD?
           #:ORDERED-LIST
           #:ORMAP
           #:PAIR?
           #:PARAGRAPH
           #:PARAMETER?
           #:PARTITION
           #:POP-RENDER-PREFIX
           #:POSITIVE?
           #:PROCEDURE-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-ALLOW-OTHER-KEYS?
           #:PROCEDURE-ARGUMENTS-KEY-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-OPTIONAL-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REQUIRED-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REST-ARGUMENT
           #:PROCEDURE-ARITY
           #:PROCEDURE?
           #:PROPER-LIST?
           #:PUSH-RENDER-PREFIX
           #:QUEUE-DELETE!
           #:QUEUE-EMPTY?
           #:QUEUE-FRONT
           #:QUEUE-INSERT!
           #:QUEUE?
           #:QUOTIENT
           #:RADIANS->DEGREES
           #:RANGE
           #:RCURRY
           #:REMOVE*
           #:REMQ
           #:REMQ*
           #:RENDER-FRESHLINE
           #:RENDER-HTML-TAG
           #:RENDER-HTML-TAG-TO-STRING
           #:RENDER-INLINE
           #:RENDER-INLINE-ESCAPED
           #:RENDER-LENGTH
           #:RENDER-MARKUP
           #:RENDER-MARKUP-HTML-TAG-TO-STRING
           #:RENDER-MARKUP-TO-STRING
           #:RENDER-NEWLINE
           #:RENDER-PREFIX
           #:RENDER-PREFORMATTED-TEXT
           #:RENDER-WITHOUT-WORD-WRAP
           #:REPEAT
           #:SAFE-VECTOR-REF
           #:SEQ
           #:SET!
           #:SET->STREAM
           #:SET-ADD
           #:SET-CAR!
           #:SET-CDR!
           #:SET-COUNT
           #:SET-EMPTY?
           #:SET-INTERSECT
           #:SET-MEMBER?
           #:SET-REMOVE
           #:SET-SUBTRACT
           #:SET-UNION
           #:SET=?
           #:SGN
           #:SORT
           #:SPLIT-AT
           #:SPLIT-STRING
           #:SPLIT-STRING-IF
           #:SQR
           #:STREAM
           #:STREAM->LIST
           #:STREAM-APPEND
           #:STREAM-CAR
           #:STREAM-CDR
           #:STREAM-COLLECT
           #:STREAM-CONS
           #:STREAM-DROP
           #:STREAM-EMPTY?
           #:STREAM-FILTER
           #:STREAM-FIRST
           #:STREAM-FLATMAP
           #:STREAM-FLATTEN
           #:STREAM-FOLD
           #:STREAM-FOR-EACH
           #:STREAM-LENGTH
           #:STREAM-MAP
           #:STREAM-MAP-SUCCESSIVE
           #:STREAM-RANGE
           #:STREAM-REF
           #:STREAM-REST
           #:STREAM-TAKE
           #:STREAM?
           #:STRING->LIST
           #:STRING-APPEND
           #:STRING-APPEND*
           #:STRING-EMPTY?
           #:STRING-FOR-EACH
           #:STRING-MAP
           #:STRING-STARTS-WITH?
           #:STRING?
           #:STRUCT
           #:STRUCT->LIST
           #:STRUCT-ACCESSORS
           #:STRUCT-COPY
           #:STRUCT?
           #:SUBSET?
           #:SWAP-ARGS
           #:SYMBOL->STRING
           #:SYMBOL?
           #:SYMBOLICATE
           #:TABLE
           #:TAKE
           #:TEXT-RENDERER?
           #:THERE-EXISTS
           #:THERE-EXISTS*
           #:UNDEFINE-BUNDLE-PRINT-OBJECT
           #:UNORDERED-LIST
           #:VECTOR->LIST
           #:VECTOR-REF
           #:VECTOR-SET!
           #:XOR
           #:ZERO?)
  (:SHADOW #:LAMBDA #:MAP #:SORT #:STREAM))
