;;;; package.lisp

(DEFPACKAGE #:SCHEMEISH.INTERNALS
  (:USE #:COMMON-LISP)
  (:EXPORT #:COMPILER-MACRO-DOCUMENTATION-SOURCE
           #:DEF
           #:DEFINE
           #:DEFINE-DESTRUCTURING
           #:DEFINE-VALUES
           #:DISABLE-GUARD-CLAUSES!
           #:DOCUMENTABLE-OBJECT?
           #:DOCUMENTATION-SOURCE?
           #:DOCUMENTATION-STRING
           #:DOCUMENTATION-TAG
           #:DOCUMENTATION-TAG-FORM
           #:DOCUMENTATION-TAG?
           #:DROPF
           #:ENABLE-GUARD-CLAUSES!
           #:EXPORT-DEFINITION
           #:EXPOSE
           #:EXPOSE-FUNCTIONS
           #:EXPOSE-VARIABLES
           #:FOR-MACROS
           #:GUARD-CLAUSES-ENABLED?
           #:GUARD-TAG
           #:GUARD-TAG-CLAUSES
           #:GUARD-TAG?
           #:INSTALL-SYNTAX!
           #:LAMBDA-FORM
           #:LET
           #:LEXICAL-BODY-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY-DEFINITION?
           #:LEXICAL-BODY-FORM
           #:LEXICAL-BODY2-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY2-DEFINITION?
           #:LEXICAL-BODY2-FORM
           #:LEXICALLY
           #:MAKE-DOCUMENTATION-TAG
           #:MAKE-GUARD-TAG
           #:MAP-DESTRUCTURING-LAMBDA-LIST
           #:MAP-ORDINARY-LAMBDA-LIST
           #:NO-COMPILE
           #:OBJECT-DOCUMENTATION-SOURCE
           #:PARSE-FUNCTION
           #:PARSE-LEXICAL-BODY
           #:PARSE-METADATA-FROM-FUNCTION-BODY
           #:READ-GUARD-TAG
           #:REGISTER-LEXICAL-BODY-DEFINITION
           #:REGISTER-LEXICAL-BODY2-DEFINITION
           #:REGISTERED-DEFINITION-NAME-FIELD
           #:REGISTERED-GUARD-CLAUSES
           #:SCM-PARAMETERS->ORDINARY-LAMBDA-LIST
           #:SET-COMPILER-MACRO-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-FROM-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-SOURCE!
           #:SET-SETF-DOCUMENTATION-SOURCE!
           #:SET-TYPE-DOCUMENTATION-SOURCE!
           #:SET-VARIABLE-DOCUMENTATION-SOURCE!
           #:SETF-DOCUMENTATION-SOURCE
           #:SPLITF
           #:TAKEF
           #:TRANSFORM-LEXICAL-BODY-DEFINE-DESTRUCTURING
           #:TRANSFORM-LEXICAL-BODY-DEFINE-SYMBOL-OR-PAIR
           #:TRANSFORM-LEXICAL-BODY-DEFINE-VALUES
           #:TRANSFORM-LEXICAL-BODY2-DEFINE-SYMBOL-OR-PAIR
           #:TYPE-DOCUMENTATION-SOURCE
           #:UNDEFINE
           #:UNINSTALL-SYNTAX!
           #:UNIQUE-SYMBOL
           #:UNREGISTER-LEXICAL-BODY-DEFINITION
           #:UNREGISTER-LEXICAL-BODY2-DEFINITION
           #:VARIABLE-DOCUMENTATION-SOURCE
           #:WITH-GUARD-CLAUSES-DISABLED
           #:WITH-GUARD-CLAUSES-ENABLED
           #:WITH-READABLE-SYMBOLS)
  (:SHADOW #:LET))

(DEFPACKAGE #:SCHEMEISH.BACKEND
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.INTERNALS #:LET)
  (:USE #:COMMON-LISP #:SCHEMEISH.INTERNALS)
  (:EXPORT #:*ESCAPE-CHARS*
           #:*LEXICAL-CONTEXT*
           #:*MARKUP-RENDER-WIDTH*
           #:*RESOLVE-PACKAGE-DESIGNATOR*
           #:*THE-EMPTY-STREAM*
           #:ALIST
           #:ALIST-FOR-EACH
           #:ALIST-HAS-KEY?
           #:ALIST-KEYS
           #:ALIST-MAP
           #:ALIST-REF
           #:ALIST-REMOVE
           #:ALIST-SET
           #:ALIST-SET*
           #:ALIST-UNION
           #:ALIST-UPDATE
           #:ALIST-VALUES
           #:ALL-PACKAGES-WITH-STRING-PREFIX
           #:AND-LET*
           #:ANDMAP
           #:APPEND*
           #:APPEND-MAP
           #:BLOCK-BODY
           #:BLOCK-NAME
           #:BLOCK-QUOTE
           #:BODY-DECLARATIONS
           #:BODY-FORMS
           #:BOLD
           #:BR
           #:BUNDLE
           #:BUNDLE-DOCUMENTATION
           #:BUNDLE-PERMISSIONS
           #:BUNDLE-PREDICATE-SYMBOL
           #:BUNDLE?
           #:CATCH-FORMS
           #:CATCH-TAG
           #:CHARS-STRING
           #:CODE
           #:CODE-BLOCK
           #:COMPOSE
           #:COMPOSE*
           #:CONJOIN
           #:CONJOIN*
           #:CONST
           #:COPY-RENDERER-WITH-NEW-STREAM
           #:CUT
           #:DECLARE?
           #:DEFINE-BUNDLE-PRINT-OBJECT
           #:DEFINE-PACKAGE
           #:DEFINE-PACKAGE-FORM
           #:DEFINE-STRUCT
           #:DEFPACKAGE-FORM
           #:DEGREES->RADIANS
           #:DELAY
           #:DISJOIN
           #:DISJOIN*
           #:DISPLAY
           #:DISPLAYLN
           #:DROP
           #:EMPTY?
           #:ENSURE-STRING
           #:EQ?
           #:EQUAL?
           #:EVAL-WHEN-FORMS
           #:EVAL-WHEN-SITUATIONS
           #:EVEN?
           #:EXTEND-PACKAGE
           #:EXTEND-PACKAGE*
           #:FILTER
           #:FILTER-MAP
           #:FILTER-NOT
           #:FILTER-PACKAGES
           #:FINDF
           #:FLATTEN
           #:FLET-BINDINGS
           #:FLET-BODY
           #:FLET-BODY-DECLARATIONS
           #:FLET-BODY-FORMS
           #:FOLDL
           #:FOLDR
           #:FOR-ALL
           #:FOR-ALL*
           #:FOR-EACH
           #:FORCE
           #:FUNCTION-BINDING-BODY
           #:FUNCTION-BINDING-BODY-DECLARATIONS
           #:FUNCTION-BINDING-BODY-FORMS
           #:FUNCTION-BINDING-NAME
           #:FUNCTION-BINDING-PARAMETERS
           #:FUNCTION-BODY-DECLARATIONS
           #:FUNCTION-BODY-FORMS
           #:FUNCTION-NAME
           #:GO-TAG
           #:GROUP
           #:GROUP-BY-PACKAGE
           #:HAS-SPECIFIC-ARITY?
           #:HASH->ALIST
           #:HASH-CLEAR!
           #:HASH-FIND-KEYF
           #:HASH-FOR-EACH
           #:HASH-KEYS
           #:HASH-MAP
           #:HASH-REF
           #:HASH-REF-DEFAULT
           #:HASH-REMOVE!
           #:HASH-SET!
           #:HASH-UPDATE!
           #:HASH-VALUES
           #:HEADING
           #:HIERARCHICAL-DEFPACKAGE-FORMS
           #:HORIZONTAL-BAR
           #:HTML-TAG
           #:HTML-TAG-ATTRIBUTE-ALIST
           #:HTML-TAG-INNER-TAGS-AND-TEXTS
           #:HTML-TAG-NAME
           #:HTML-TAG?
           #:IF-ELSE
           #:IF-TEST
           #:IF-THEN
           #:IGNORE-ARGS
           #:INDEPENDENT-PACKAGE?
           #:INDEPENDENT-PACKAGES
           #:INLINE-MARKUP
           #:INLINE-MARKUP?
           #:INLINE-TEXT
           #:INLINE-TEXT?
           #:INTERSPERSE
           #:ITALIC
           #:JOIN-STRINGS
           #:LABELS-BINDINGS
           #:LABELS-BODY
           #:LABELS-BODY-DECLARATIONS
           #:LABELS-BODY-FORMS
           #:LAMBDA
           #:LAMBDA-BODY
           #:LAMBDA-BODY-DECLARATIONS
           #:LAMBDA-BODY-FORMS
           #:LAMBDA-PARAMETERS
           #:LCURRY
           #:LET*-BINDINGS
           #:LET*-BODY
           #:LET*-BODY-DECLARATIONS
           #:LET*-BODY-FORMS
           #:LET-BINDINGS
           #:LET-BODY
           #:LET-BODY-DECLARATIONS
           #:LET-BODY-FORMS
           #:LETREC
           #:LINK
           #:LIST->STREAM
           #:LIST->STRING
           #:LIST->VECTOR
           #:LIST-ITEM-TAG
           #:LIST-REF
           #:LIST-SET
           #:LIST-TAIL
           #:LIST-TYPE
           #:LIST-UPDATE
           #:LIST?
           #:LOAD-TIME-VALUE-FORM
           #:LOAD-TIME-VALUE-READ-ONLY-P
           #:LOCALLY-BODY
           #:LOCALLY-BODY-DECLARATIONS
           #:LOCALLY-BODY-FORMS
           #:MACRO-FUNCTION-APPLICATION?
           #:MACROLET-BINDINGS
           #:MACROLET-BODY
           #:MACROLET-BODY-DECLARATIONS
           #:MACROLET-BODY-FORMS
           #:MAKE-BUNDLE-PREDICATE
           #:MAKE-HTML-TAG
           #:MAKE-INLINE-MARKUP
           #:MAKE-KEYWORD
           #:MAKE-MARKUP
           #:MAKE-QUEUE
           #:MAKE-TEXT-RENDERER
           #:MAKE-TRANSFORMER
           #:MAP
           #:MAP-SUCCESSIVE
           #:MARKUP
           #:MARKUP-CONSTRUCTOR
           #:MARKUP-CONSTRUCTOR-FORM
           #:MARKUP-HTML-TAG
           #:MARKUP-RENDER-TEXT
           #:MARKUP-STRING-RENDERER
           #:MARKUP?
           #:MEMF
           #:MEMO-PROC
           #:MULTIPLE-VALUE-CALL-ARGUMENTS
           #:MULTIPLE-VALUE-CALL-FUNCTION
           #:MULTIPLE-VALUE-PROG1-FORMS
           #:MULTIPLE-VALUE-PROG1-VALUES-FORM
           #:NAND
           #:NEGATIVE?
           #:NEWLINE
           #:NICKNAME-PACKAGE
           #:NOR
           #:NULL?
           #:NUMBER->STRING
           #:NUMBER?
           #:ODD?
           #:ORDERED-LIST
           #:ORMAP
           #:PACKAGE-DEFINED-AND-EXPORTED-SYMBOLS
           #:PACKAGE-DELETE
           #:PACKAGE-DEPENDENCIES
           #:PACKAGE-EXPORT
           #:PACKAGE-EXPORTED-SYMBOLS
           #:PACKAGE-EXTERNAL-SYMBOLS
           #:PACKAGE-EXTERNAL-SYMBOLS-FROM
           #:PACKAGE-FILE-CONTENTS
           #:PACKAGE-FIND
           #:PACKAGE-HIERARCHY
           #:PACKAGE-IMPORT-FROM
           #:PACKAGE-IMPORT-FROMS
           #:PACKAGE-IMPORTED-SYMBOLS
           #:PACKAGE-NON-SHADOWING-SYMBOLS
           #:PACKAGE-RE-EXPORT-SHADOWING
           #:PACKAGE-SHADOW
           #:PACKAGE-SHADOWING-EXPORT
           #:PACKAGE-SHADOWING-IMPORT-FROM
           #:PACKAGE-SHADOWING-IMPORT-FROMS
           #:PACKAGE-SYMBOLS
           #:PACKAGE-UNUSED-SYMBOLS
           #:PACKAGE-USE
           #:PACKAGE-USE-AND-EXPORT-SHADOWING
           #:PACKAGE-USE-SHADOWING
           #:PACKAGE-USED-SYMBOLS
           #:PACKAGE?
           #:PAIR?
           #:PARAGRAPH
           #:PARAMETER?
           #:PARSE-TAGBODY
           #:PARTITION
           #:POP-RENDER-PREFIX
           #:POSITIVE?
           #:PROCEDURE-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-ALLOW-OTHER-KEYS?
           #:PROCEDURE-ARGUMENTS-KEY-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-OPTIONAL-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REQUIRED-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REST-ARGUMENT
           #:PROCEDURE-ARITY
           #:PROCEDURE?
           #:PROGN-FORMS
           #:PROPER-LIST?
           #:PUSH-RENDER-PREFIX
           #:QUEUE-DELETE!
           #:QUEUE-EMPTY?
           #:QUEUE-FRONT
           #:QUEUE-INSERT!
           #:QUEUE?
           #:QUOTE-EXPR
           #:QUOTIENT
           #:RADIANS->DEGREES
           #:RANGE
           #:RCURRY
           #:REMOVE*
           #:REMQ
           #:REMQ*
           #:RENDER-FRESHLINE
           #:RENDER-HTML-TAG
           #:RENDER-HTML-TAG-TO-STRING
           #:RENDER-INLINE
           #:RENDER-INLINE-ESCAPED
           #:RENDER-LENGTH
           #:RENDER-MARKUP
           #:RENDER-MARKUP-HTML-TAG-TO-STRING
           #:RENDER-MARKUP-TO-STRING
           #:RENDER-NEWLINE
           #:RENDER-PREFIX
           #:RENDER-PREFORMATTED-TEXT
           #:RENDER-WITHOUT-WORD-WRAP
           #:REPEAT
           #:RETURN-FROM-NAME
           #:RETURN-FROM-VALUE
           #:SAFE-VECTOR-REF
           #:SEQ
           #:SET!
           #:SET->STREAM
           #:SET-ADD
           #:SET-CAR!
           #:SET-CDR!
           #:SET-COUNT
           #:SET-EMPTY?
           #:SET-INTERSECT
           #:SET-MEMBER?
           #:SET-REMOVE
           #:SET-SUBTRACT
           #:SET-UNION
           #:SET=?
           #:SETQ-PAIRS
           #:SGN
           #:SORT
           #:SPLIT-AT
           #:SPLIT-STRING
           #:SPLIT-STRING-IF
           #:SQR
           #:STREAM
           #:STREAM->LIST
           #:STREAM-APPEND
           #:STREAM-CAR
           #:STREAM-CDR
           #:STREAM-COLLECT
           #:STREAM-CONS
           #:STREAM-DROP
           #:STREAM-EMPTY?
           #:STREAM-FILTER
           #:STREAM-FIRST
           #:STREAM-FLATMAP
           #:STREAM-FLATTEN
           #:STREAM-FOLD
           #:STREAM-FOR-EACH
           #:STREAM-LENGTH
           #:STREAM-MAP
           #:STREAM-MAP-SUCCESSIVE
           #:STREAM-RANGE
           #:STREAM-REF
           #:STREAM-REST
           #:STREAM-TAKE
           #:STREAM?
           #:STRING->LIST
           #:STRING-APPEND
           #:STRING-APPEND*
           #:STRING-EMPTY?
           #:STRING-FOR-EACH
           #:STRING-MAP
           #:STRING-STARTS-WITH?
           #:STRING?
           #:STRUCT
           #:STRUCT->LIST
           #:STRUCT-ACCESSORS
           #:STRUCT-COPY
           #:STRUCT?
           #:SUBSET?
           #:SWAP-ARGS
           #:SYMBOL->STRING
           #:SYMBOL-IN-PACKAGE?
           #:SYMBOL-MACROLET-BINDINGS
           #:SYMBOL-MACROLET-BODY
           #:SYMBOL-MACROLET-BODY-DECLARATIONS
           #:SYMBOL-MACROLET-BODY-FORMS
           #:SYMBOL?
           #:SYMBOLICATE
           #:SYMBOLS-IN-PACKAGE
           #:SYMBOLS-INTERNED-IN-PACKAGE
           #:TABLE
           #:TAGBODY-TAGS-AND-STATEMENTS
           #:TAKE
           #:TEXT-RENDERER
           #:TEXT-RENDERER-COPY-WITH-NEW-STREAM
           #:TEXT-RENDERER-POP-PREFIX
           #:TEXT-RENDERER-PUSH-PREFIX
           #:TEXT-RENDERER-RENDER-FRESHLINE
           #:TEXT-RENDERER-RENDER-INLINE
           #:TEXT-RENDERER-RENDER-NEWLINE
           #:TEXT-RENDERER-RENDER-PREFIX
           #:TEXT-RENDERER-RENDER-PREFORMATTED-TEXT
           #:TEXT-RENDERER-RENDER-WITHOUT-WORD-WRAP
           #:TEXT-RENDERER?
           #:THE-FORM
           #:THE-VALUE-TYPE
           #:THERE-EXISTS
           #:THERE-EXISTS*
           #:THROW-RESULT
           #:THROW-TAG
           #:TRANSFORM
           #:TRANSFORM-EXPRESSION
           #:TRANSFORM-IN-LEXICAL-ENVIRONMENT
           #:TRANSFORMER
           #:TRANSFORMER-TRANSFORM-ATOM
           #:TRANSFORMER-TRANSFORM-CYCLIC-LIST
           #:TRANSFORMER-TRANSFORM-DOTTED-LIST
           #:TRANSFORMER-TRANSFORM-PROPER-LIST
           #:TRANSFORMER-TRANSFORM-SPECIAL-FORM-TABLE
           #:TRANSFORMER?
           #:UNDEFINE-BUNDLE-PRINT-OBJECT
           #:UNINTERNED
           #:UNORDERED-LIST
           #:UNWIND-PROTECT-CLEANUP
           #:UNWIND-PROTECT-PROTECTED
           #:VECTOR->LIST
           #:VECTOR-REF
           #:VECTOR-SET!
           #:WITH-TEMPORARY-PACKAGE
           #:WORD-WRAP-LINE
           #:XOR
           #:ZERO?)
  (:SHADOW #:LAMBDA #:MAP #:SORT #:STREAM))

(DEFPACKAGE #:SCHEMEISH.SCHEMEISH
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.BACKEND #:LAMBDA #:MAP #:SORT #:STREAM)
  (:SHADOWING-IMPORT-FROM #:SCHEMEISH.INTERNALS #:LET)
  (:USE #:COMMON-LISP #:SCHEMEISH.BACKEND #:SCHEMEISH.INTERNALS)
  (:EXPORT #:&ALLOW-OTHER-KEYS
           #:&AUX
           #:&BODY
           #:&ENVIRONMENT
           #:&KEY
           #:&OPTIONAL
           #:&REST
           #:&WHOLE
           #:*
           #:**
           #:***
           #:*BREAK-ON-SIGNALS*
           #:*COMPILE-FILE-PATHNAME*
           #:*COMPILE-FILE-TRUENAME*
           #:*COMPILE-PRINT*
           #:*COMPILE-VERBOSE*
           #:*DEBUG-IO*
           #:*DEBUGGER-HOOK*
           #:*DEFAULT-PATHNAME-DEFAULTS*
           #:*ERROR-OUTPUT*
           #:*ESCAPE-CHARS*
           #:*FEATURES*
           #:*GENSYM-COUNTER*
           #:*LEXICAL-CONTEXT*
           #:*LOAD-PATHNAME*
           #:*LOAD-PRINT*
           #:*LOAD-TRUENAME*
           #:*LOAD-VERBOSE*
           #:*MACROEXPAND-HOOK*
           #:*MARKUP-RENDER-WIDTH*
           #:*MODULES*
           #:*PACKAGE*
           #:*PRINT-ARRAY*
           #:*PRINT-BASE*
           #:*PRINT-CASE*
           #:*PRINT-CIRCLE*
           #:*PRINT-ESCAPE*
           #:*PRINT-GENSYM*
           #:*PRINT-LENGTH*
           #:*PRINT-LEVEL*
           #:*PRINT-LINES*
           #:*PRINT-MISER-WIDTH*
           #:*PRINT-PPRINT-DISPATCH*
           #:*PRINT-PRETTY*
           #:*PRINT-RADIX*
           #:*PRINT-READABLY*
           #:*PRINT-RIGHT-MARGIN*
           #:*QUERY-IO*
           #:*RANDOM-STATE*
           #:*READ-BASE*
           #:*READ-DEFAULT-FLOAT-FORMAT*
           #:*READ-EVAL*
           #:*READ-SUPPRESS*
           #:*READTABLE*
           #:*RESOLVE-PACKAGE-DESIGNATOR*
           #:*STANDARD-INPUT*
           #:*STANDARD-OUTPUT*
           #:*TERMINAL-IO*
           #:*THE-EMPTY-STREAM*
           #:*TRACE-OUTPUT*
           #:+
           #:++
           #:+++
           #:-
           #:/
           #://
           #:///
           #:/=
           #:1+
           #:1-
           #:<
           #:<=
           #:=
           #:>
           #:>=
           #:ABORT
           #:ABS
           #:ACONS
           #:ACOS
           #:ACOSH
           #:ADD-METHOD
           #:ADJOIN
           #:ADJUST-ARRAY
           #:ADJUSTABLE-ARRAY-P
           #:ALIST
           #:ALIST-FOR-EACH
           #:ALIST-HAS-KEY?
           #:ALIST-KEYS
           #:ALIST-MAP
           #:ALIST-REF
           #:ALIST-REMOVE
           #:ALIST-SET
           #:ALIST-SET*
           #:ALIST-UNION
           #:ALIST-UPDATE
           #:ALIST-VALUES
           #:ALL-PACKAGES-WITH-STRING-PREFIX
           #:ALLOCATE-INSTANCE
           #:ALPHA-CHAR-P
           #:ALPHANUMERICP
           #:AND
           #:AND-LET*
           #:ANDMAP
           #:APPEND
           #:APPEND*
           #:APPEND-MAP
           #:APPLY
           #:APROPOS
           #:APROPOS-LIST
           #:AREF
           #:ARITHMETIC-ERROR
           #:ARITHMETIC-ERROR-OPERANDS
           #:ARITHMETIC-ERROR-OPERATION
           #:ARRAY
           #:ARRAY-DIMENSION
           #:ARRAY-DIMENSION-LIMIT
           #:ARRAY-DIMENSIONS
           #:ARRAY-DISPLACEMENT
           #:ARRAY-ELEMENT-TYPE
           #:ARRAY-HAS-FILL-POINTER-P
           #:ARRAY-IN-BOUNDS-P
           #:ARRAY-RANK
           #:ARRAY-RANK-LIMIT
           #:ARRAY-ROW-MAJOR-INDEX
           #:ARRAY-TOTAL-SIZE
           #:ARRAY-TOTAL-SIZE-LIMIT
           #:ARRAYP
           #:ASH
           #:ASIN
           #:ASINH
           #:ASSERT
           #:ASSOC
           #:ASSOC-IF
           #:ASSOC-IF-NOT
           #:ATAN
           #:ATANH
           #:ATOM
           #:BASE-CHAR
           #:BASE-STRING
           #:BIGNUM
           #:BIT
           #:BIT-AND
           #:BIT-ANDC1
           #:BIT-ANDC2
           #:BIT-EQV
           #:BIT-IOR
           #:BIT-NAND
           #:BIT-NOR
           #:BIT-NOT
           #:BIT-ORC1
           #:BIT-ORC2
           #:BIT-VECTOR
           #:BIT-VECTOR-P
           #:BIT-XOR
           #:BLOCK
           #:BLOCK-BODY
           #:BLOCK-NAME
           #:BLOCK-QUOTE
           #:BODY-DECLARATIONS
           #:BODY-FORMS
           #:BOLD
           #:BOOLE
           #:BOOLE-1
           #:BOOLE-2
           #:BOOLE-AND
           #:BOOLE-ANDC1
           #:BOOLE-ANDC2
           #:BOOLE-C1
           #:BOOLE-C2
           #:BOOLE-CLR
           #:BOOLE-EQV
           #:BOOLE-IOR
           #:BOOLE-NAND
           #:BOOLE-NOR
           #:BOOLE-ORC1
           #:BOOLE-ORC2
           #:BOOLE-SET
           #:BOOLE-XOR
           #:BOOLEAN
           #:BOTH-CASE-P
           #:BOUNDP
           #:BR
           #:BREAK
           #:BROADCAST-STREAM
           #:BROADCAST-STREAM-STREAMS
           #:BUILT-IN-CLASS
           #:BUNDLE
           #:BUNDLE-DOCUMENTATION
           #:BUNDLE-PERMISSIONS
           #:BUNDLE-PREDICATE-SYMBOL
           #:BUNDLE?
           #:BUTLAST
           #:BYTE
           #:BYTE-POSITION
           #:BYTE-SIZE
           #:CAAAAR
           #:CAAADR
           #:CAAAR
           #:CAADAR
           #:CAADDR
           #:CAADR
           #:CAAR
           #:CADAAR
           #:CADADR
           #:CADAR
           #:CADDAR
           #:CADDDR
           #:CADDR
           #:CADR
           #:CALL-ARGUMENTS-LIMIT
           #:CALL-METHOD
           #:CALL-NEXT-METHOD
           #:CAR
           #:CASE
           #:CATCH
           #:CATCH-FORMS
           #:CATCH-TAG
           #:CCASE
           #:CDAAAR
           #:CDAADR
           #:CDAAR
           #:CDADAR
           #:CDADDR
           #:CDADR
           #:CDAR
           #:CDDAAR
           #:CDDADR
           #:CDDAR
           #:CDDDAR
           #:CDDDDR
           #:CDDDR
           #:CDDR
           #:CDR
           #:CEILING
           #:CELL-ERROR
           #:CELL-ERROR-NAME
           #:CERROR
           #:CHANGE-CLASS
           #:CHAR
           #:CHAR-CODE
           #:CHAR-CODE-LIMIT
           #:CHAR-DOWNCASE
           #:CHAR-EQUAL
           #:CHAR-GREATERP
           #:CHAR-INT
           #:CHAR-LESSP
           #:CHAR-NAME
           #:CHAR-NOT-EQUAL
           #:CHAR-NOT-GREATERP
           #:CHAR-NOT-LESSP
           #:CHAR-UPCASE
           #:CHAR/=
           #:CHAR<
           #:CHAR<=
           #:CHAR=
           #:CHAR>
           #:CHAR>=
           #:CHARACTER
           #:CHARACTERP
           #:CHARS-STRING
           #:CHECK-TYPE
           #:CIS
           #:CLASS
           #:CLASS-NAME
           #:CLASS-OF
           #:CLEAR-INPUT
           #:CLEAR-OUTPUT
           #:CLOSE
           #:CLRHASH
           #:CODE
           #:CODE-BLOCK
           #:CODE-CHAR
           #:COERCE
           #:COMPILATION-SPEED
           #:COMPILE
           #:COMPILE-FILE
           #:COMPILE-FILE-PATHNAME
           #:COMPILED-FUNCTION
           #:COMPILED-FUNCTION-P
           #:COMPILER-MACRO
           #:COMPILER-MACRO-DOCUMENTATION-SOURCE
           #:COMPILER-MACRO-FUNCTION
           #:COMPLEMENT
           #:COMPLEX
           #:COMPLEXP
           #:COMPOSE
           #:COMPOSE*
           #:COMPUTE-APPLICABLE-METHODS
           #:COMPUTE-RESTARTS
           #:CONCATENATE
           #:CONCATENATED-STREAM
           #:CONCATENATED-STREAM-STREAMS
           #:COND
           #:CONDITION
           #:CONJOIN
           #:CONJOIN*
           #:CONJUGATE
           #:CONS
           #:CONSP
           #:CONST
           #:CONSTANTLY
           #:CONSTANTP
           #:CONTINUE
           #:CONTROL-ERROR
           #:COPY-ALIST
           #:COPY-LIST
           #:COPY-PPRINT-DISPATCH
           #:COPY-READTABLE
           #:COPY-RENDERER-WITH-NEW-STREAM
           #:COPY-SEQ
           #:COPY-STRUCTURE
           #:COPY-SYMBOL
           #:COPY-TREE
           #:COS
           #:COSH
           #:COUNT
           #:COUNT-IF
           #:COUNT-IF-NOT
           #:CTYPECASE
           #:CUT
           #:DEBUG
           #:DECF
           #:DECLAIM
           #:DECLARATION
           #:DECLARE
           #:DECLARE?
           #:DECODE-FLOAT
           #:DECODE-UNIVERSAL-TIME
           #:DEF
           #:DEFCLASS
           #:DEFCONSTANT
           #:DEFGENERIC
           #:DEFINE
           #:DEFINE-BUNDLE-PRINT-OBJECT
           #:DEFINE-COMPILER-MACRO
           #:DEFINE-CONDITION
           #:DEFINE-DESTRUCTURING
           #:DEFINE-METHOD-COMBINATION
           #:DEFINE-MODIFY-MACRO
           #:DEFINE-PACKAGE
           #:DEFINE-PACKAGE-FORM
           #:DEFINE-SETF-EXPANDER
           #:DEFINE-STRUCT
           #:DEFINE-SYMBOL-MACRO
           #:DEFINE-VALUES
           #:DEFMACRO
           #:DEFMETHOD
           #:DEFPACKAGE
           #:DEFPACKAGE-FORM
           #:DEFPARAMETER
           #:DEFSETF
           #:DEFSTRUCT
           #:DEFTYPE
           #:DEFUN
           #:DEFVAR
           #:DEGREES->RADIANS
           #:DELAY
           #:DELETE
           #:DELETE-DUPLICATES
           #:DELETE-FILE
           #:DELETE-IF
           #:DELETE-IF-NOT
           #:DELETE-PACKAGE
           #:DENOMINATOR
           #:DEPOSIT-FIELD
           #:DESCRIBE
           #:DESCRIBE-OBJECT
           #:DESTRUCTURING-BIND
           #:DIGIT-CHAR
           #:DIGIT-CHAR-P
           #:DIRECTORY
           #:DIRECTORY-NAMESTRING
           #:DISABLE-GUARD-CLAUSES!
           #:DISASSEMBLE
           #:DISJOIN
           #:DISJOIN*
           #:DISPLAY
           #:DISPLAYLN
           #:DIVISION-BY-ZERO
           #:DO
           #:DO*
           #:DO-ALL-SYMBOLS
           #:DO-EXTERNAL-SYMBOLS
           #:DO-SYMBOLS
           #:DOCUMENTABLE-OBJECT?
           #:DOCUMENTATION
           #:DOCUMENTATION-SOURCE?
           #:DOCUMENTATION-STRING
           #:DOCUMENTATION-TAG
           #:DOCUMENTATION-TAG-FORM
           #:DOCUMENTATION-TAG?
           #:DOLIST
           #:DOTIMES
           #:DOUBLE-FLOAT
           #:DOUBLE-FLOAT-EPSILON
           #:DOUBLE-FLOAT-NEGATIVE-EPSILON
           #:DPB
           #:DRIBBLE
           #:DROP
           #:DROPF
           #:DYNAMIC-EXTENT
           #:ECASE
           #:ECHO-STREAM
           #:ECHO-STREAM-INPUT-STREAM
           #:ECHO-STREAM-OUTPUT-STREAM
           #:ED
           #:EIGHTH
           #:ELT
           #:EMPTY?
           #:ENABLE-GUARD-CLAUSES!
           #:ENCODE-UNIVERSAL-TIME
           #:END-OF-FILE
           #:ENDP
           #:ENOUGH-NAMESTRING
           #:ENSURE-DIRECTORIES-EXIST
           #:ENSURE-GENERIC-FUNCTION
           #:ENSURE-STRING
           #:EQ
           #:EQ?
           #:EQL
           #:EQUAL
           #:EQUAL?
           #:EQUALP
           #:ERROR
           #:ETYPECASE
           #:EVAL
           #:EVAL-WHEN
           #:EVAL-WHEN-FORMS
           #:EVAL-WHEN-SITUATIONS
           #:EVEN?
           #:EVENP
           #:EVERY
           #:EXP
           #:EXPORT
           #:EXPORT-DEFINITION
           #:EXPOSE
           #:EXPOSE-FUNCTIONS
           #:EXPOSE-VARIABLES
           #:EXPT
           #:EXTEND-PACKAGE
           #:EXTEND-PACKAGE*
           #:EXTENDED-CHAR
           #:FBOUNDP
           #:FCEILING
           #:FDEFINITION
           #:FFLOOR
           #:FIFTH
           #:FILE-AUTHOR
           #:FILE-ERROR
           #:FILE-ERROR-PATHNAME
           #:FILE-LENGTH
           #:FILE-NAMESTRING
           #:FILE-POSITION
           #:FILE-STREAM
           #:FILE-STRING-LENGTH
           #:FILE-WRITE-DATE
           #:FILL
           #:FILL-POINTER
           #:FILTER
           #:FILTER-MAP
           #:FILTER-NOT
           #:FILTER-PACKAGES
           #:FIND
           #:FIND-ALL-SYMBOLS
           #:FIND-CLASS
           #:FIND-IF
           #:FIND-IF-NOT
           #:FIND-METHOD
           #:FIND-PACKAGE
           #:FIND-RESTART
           #:FIND-SYMBOL
           #:FINDF
           #:FINISH-OUTPUT
           #:FIRST
           #:FIXNUM
           #:FLATTEN
           #:FLET
           #:FLET-BINDINGS
           #:FLET-BODY
           #:FLET-BODY-DECLARATIONS
           #:FLET-BODY-FORMS
           #:FLOAT
           #:FLOAT-DIGITS
           #:FLOAT-PRECISION
           #:FLOAT-RADIX
           #:FLOAT-SIGN
           #:FLOATING-POINT-INEXACT
           #:FLOATING-POINT-INVALID-OPERATION
           #:FLOATING-POINT-OVERFLOW
           #:FLOATING-POINT-UNDERFLOW
           #:FLOATP
           #:FLOOR
           #:FMAKUNBOUND
           #:FOLDL
           #:FOLDR
           #:FOR-ALL
           #:FOR-ALL*
           #:FOR-EACH
           #:FOR-MACROS
           #:FORCE
           #:FORCE-OUTPUT
           #:FORMAT
           #:FORMATTER
           #:FOURTH
           #:FRESH-LINE
           #:FROUND
           #:FTRUNCATE
           #:FTYPE
           #:FUNCALL
           #:FUNCTION
           #:FUNCTION-BINDING-BODY
           #:FUNCTION-BINDING-BODY-DECLARATIONS
           #:FUNCTION-BINDING-BODY-FORMS
           #:FUNCTION-BINDING-NAME
           #:FUNCTION-BINDING-PARAMETERS
           #:FUNCTION-BODY-DECLARATIONS
           #:FUNCTION-BODY-FORMS
           #:FUNCTION-KEYWORDS
           #:FUNCTION-LAMBDA-EXPRESSION
           #:FUNCTION-NAME
           #:FUNCTIONP
           #:GCD
           #:GENERIC-FUNCTION
           #:GENSYM
           #:GENTEMP
           #:GET
           #:GET-DECODED-TIME
           #:GET-DISPATCH-MACRO-CHARACTER
           #:GET-INTERNAL-REAL-TIME
           #:GET-INTERNAL-RUN-TIME
           #:GET-MACRO-CHARACTER
           #:GET-OUTPUT-STREAM-STRING
           #:GET-PROPERTIES
           #:GET-SETF-EXPANSION
           #:GET-UNIVERSAL-TIME
           #:GETF
           #:GETHASH
           #:GO
           #:GO-TAG
           #:GRAPHIC-CHAR-P
           #:GROUP
           #:GROUP-BY-PACKAGE
           #:GUARD-CLAUSES-ENABLED?
           #:GUARD-TAG
           #:GUARD-TAG-CLAUSES
           #:GUARD-TAG?
           #:HANDLER-BIND
           #:HANDLER-CASE
           #:HAS-SPECIFIC-ARITY?
           #:HASH->ALIST
           #:HASH-CLEAR!
           #:HASH-FIND-KEYF
           #:HASH-FOR-EACH
           #:HASH-KEYS
           #:HASH-MAP
           #:HASH-REF
           #:HASH-REF-DEFAULT
           #:HASH-REMOVE!
           #:HASH-SET!
           #:HASH-TABLE
           #:HASH-TABLE-COUNT
           #:HASH-TABLE-P
           #:HASH-TABLE-REHASH-SIZE
           #:HASH-TABLE-REHASH-THRESHOLD
           #:HASH-TABLE-SIZE
           #:HASH-TABLE-TEST
           #:HASH-UPDATE!
           #:HASH-VALUES
           #:HEADING
           #:HIERARCHICAL-DEFPACKAGE-FORMS
           #:HORIZONTAL-BAR
           #:HOST-NAMESTRING
           #:HTML-TAG
           #:HTML-TAG-ATTRIBUTE-ALIST
           #:HTML-TAG-INNER-TAGS-AND-TEXTS
           #:HTML-TAG-NAME
           #:HTML-TAG?
           #:IDENTITY
           #:IF
           #:IF-ELSE
           #:IF-TEST
           #:IF-THEN
           #:IGNORABLE
           #:IGNORE
           #:IGNORE-ARGS
           #:IGNORE-ERRORS
           #:IMAGPART
           #:IMPORT
           #:IN-PACKAGE
           #:INCF
           #:INDEPENDENT-PACKAGE?
           #:INDEPENDENT-PACKAGES
           #:INITIALIZE-INSTANCE
           #:INLINE
           #:INLINE-MARKUP
           #:INLINE-MARKUP?
           #:INLINE-TEXT
           #:INLINE-TEXT?
           #:INPUT-STREAM-P
           #:INSPECT
           #:INSTALL-SYNTAX!
           #:INTEGER
           #:INTEGER-DECODE-FLOAT
           #:INTEGER-LENGTH
           #:INTEGERP
           #:INTERACTIVE-STREAM-P
           #:INTERN
           #:INTERNAL-TIME-UNITS-PER-SECOND
           #:INTERSECTION
           #:INTERSPERSE
           #:INVALID-METHOD-ERROR
           #:INVOKE-DEBUGGER
           #:INVOKE-RESTART
           #:INVOKE-RESTART-INTERACTIVELY
           #:ISQRT
           #:ITALIC
           #:JOIN-STRINGS
           #:KEYWORD
           #:KEYWORDP
           #:LABELS
           #:LABELS-BINDINGS
           #:LABELS-BODY
           #:LABELS-BODY-DECLARATIONS
           #:LABELS-BODY-FORMS
           #:LAMBDA
           #:LAMBDA-BODY
           #:LAMBDA-BODY-DECLARATIONS
           #:LAMBDA-BODY-FORMS
           #:LAMBDA-FORM
           #:LAMBDA-LIST-KEYWORDS
           #:LAMBDA-PARAMETERS
           #:LAMBDA-PARAMETERS-LIMIT
           #:LAST
           #:LCM
           #:LCURRY
           #:LDB
           #:LDB-TEST
           #:LDIFF
           #:LEAST-NEGATIVE-DOUBLE-FLOAT
           #:LEAST-NEGATIVE-LONG-FLOAT
           #:LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT
           #:LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT
           #:LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT
           #:LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT
           #:LEAST-NEGATIVE-SHORT-FLOAT
           #:LEAST-NEGATIVE-SINGLE-FLOAT
           #:LEAST-POSITIVE-DOUBLE-FLOAT
           #:LEAST-POSITIVE-LONG-FLOAT
           #:LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT
           #:LEAST-POSITIVE-NORMALIZED-LONG-FLOAT
           #:LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT
           #:LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT
           #:LEAST-POSITIVE-SHORT-FLOAT
           #:LEAST-POSITIVE-SINGLE-FLOAT
           #:LENGTH
           #:LET
           #:LET*
           #:LET*-BINDINGS
           #:LET*-BODY
           #:LET*-BODY-DECLARATIONS
           #:LET*-BODY-FORMS
           #:LET-BINDINGS
           #:LET-BODY
           #:LET-BODY-DECLARATIONS
           #:LET-BODY-FORMS
           #:LETREC
           #:LEXICAL-BODY-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY-DEFINITION?
           #:LEXICAL-BODY-FORM
           #:LEXICAL-BODY2-DEFINITION-DOCUMENTATIONS
           #:LEXICAL-BODY2-DEFINITION?
           #:LEXICAL-BODY2-FORM
           #:LEXICALLY
           #:LINK
           #:LISP-IMPLEMENTATION-TYPE
           #:LISP-IMPLEMENTATION-VERSION
           #:LIST
           #:LIST*
           #:LIST->STREAM
           #:LIST->STRING
           #:LIST->VECTOR
           #:LIST-ALL-PACKAGES
           #:LIST-ITEM-TAG
           #:LIST-LENGTH
           #:LIST-REF
           #:LIST-SET
           #:LIST-TAIL
           #:LIST-TYPE
           #:LIST-UPDATE
           #:LIST?
           #:LISTEN
           #:LISTP
           #:LOAD
           #:LOAD-LOGICAL-PATHNAME-TRANSLATIONS
           #:LOAD-TIME-VALUE
           #:LOAD-TIME-VALUE-FORM
           #:LOAD-TIME-VALUE-READ-ONLY-P
           #:LOCALLY
           #:LOCALLY-BODY
           #:LOCALLY-BODY-DECLARATIONS
           #:LOCALLY-BODY-FORMS
           #:LOG
           #:LOGAND
           #:LOGANDC1
           #:LOGANDC2
           #:LOGBITP
           #:LOGCOUNT
           #:LOGEQV
           #:LOGICAL-PATHNAME
           #:LOGICAL-PATHNAME-TRANSLATIONS
           #:LOGIOR
           #:LOGNAND
           #:LOGNOR
           #:LOGNOT
           #:LOGORC1
           #:LOGORC2
           #:LOGTEST
           #:LOGXOR
           #:LONG-FLOAT
           #:LONG-FLOAT-EPSILON
           #:LONG-FLOAT-NEGATIVE-EPSILON
           #:LONG-SITE-NAME
           #:LOOP
           #:LOOP-FINISH
           #:LOWER-CASE-P
           #:MACHINE-INSTANCE
           #:MACHINE-TYPE
           #:MACHINE-VERSION
           #:MACRO-FUNCTION
           #:MACRO-FUNCTION-APPLICATION?
           #:MACROEXPAND
           #:MACROEXPAND-1
           #:MACROLET
           #:MACROLET-BINDINGS
           #:MACROLET-BODY
           #:MACROLET-BODY-DECLARATIONS
           #:MACROLET-BODY-FORMS
           #:MAKE-ARRAY
           #:MAKE-BROADCAST-STREAM
           #:MAKE-BUNDLE-PREDICATE
           #:MAKE-CONCATENATED-STREAM
           #:MAKE-CONDITION
           #:MAKE-DISPATCH-MACRO-CHARACTER
           #:MAKE-DOCUMENTATION-TAG
           #:MAKE-ECHO-STREAM
           #:MAKE-GUARD-TAG
           #:MAKE-HASH-TABLE
           #:MAKE-HTML-TAG
           #:MAKE-INLINE-MARKUP
           #:MAKE-INSTANCE
           #:MAKE-INSTANCES-OBSOLETE
           #:MAKE-KEYWORD
           #:MAKE-LIST
           #:MAKE-LOAD-FORM
           #:MAKE-LOAD-FORM-SAVING-SLOTS
           #:MAKE-MARKUP
           #:MAKE-METHOD
           #:MAKE-PACKAGE
           #:MAKE-PATHNAME
           #:MAKE-QUEUE
           #:MAKE-RANDOM-STATE
           #:MAKE-SEQUENCE
           #:MAKE-STRING
           #:MAKE-STRING-INPUT-STREAM
           #:MAKE-STRING-OUTPUT-STREAM
           #:MAKE-SYMBOL
           #:MAKE-SYNONYM-STREAM
           #:MAKE-TEXT-RENDERER
           #:MAKE-TRANSFORMER
           #:MAKE-TWO-WAY-STREAM
           #:MAKUNBOUND
           #:MAP
           #:MAP-DESTRUCTURING-LAMBDA-LIST
           #:MAP-INTO
           #:MAP-ORDINARY-LAMBDA-LIST
           #:MAP-SUCCESSIVE
           #:MAPC
           #:MAPCAN
           #:MAPCAR
           #:MAPCON
           #:MAPHASH
           #:MAPL
           #:MAPLIST
           #:MARKUP
           #:MARKUP-CONSTRUCTOR
           #:MARKUP-CONSTRUCTOR-FORM
           #:MARKUP-HTML-TAG
           #:MARKUP-RENDER-TEXT
           #:MARKUP-STRING-RENDERER
           #:MARKUP?
           #:MASK-FIELD
           #:MAX
           #:MEMBER
           #:MEMBER-IF
           #:MEMBER-IF-NOT
           #:MEMF
           #:MEMO-PROC
           #:MERGE
           #:MERGE-PATHNAMES
           #:METHOD
           #:METHOD-COMBINATION
           #:METHOD-COMBINATION-ERROR
           #:METHOD-QUALIFIERS
           #:MIN
           #:MINUSP
           #:MISMATCH
           #:MOD
           #:MOST-NEGATIVE-DOUBLE-FLOAT
           #:MOST-NEGATIVE-FIXNUM
           #:MOST-NEGATIVE-LONG-FLOAT
           #:MOST-NEGATIVE-SHORT-FLOAT
           #:MOST-NEGATIVE-SINGLE-FLOAT
           #:MOST-POSITIVE-DOUBLE-FLOAT
           #:MOST-POSITIVE-FIXNUM
           #:MOST-POSITIVE-LONG-FLOAT
           #:MOST-POSITIVE-SHORT-FLOAT
           #:MOST-POSITIVE-SINGLE-FLOAT
           #:MUFFLE-WARNING
           #:MULTIPLE-VALUE-BIND
           #:MULTIPLE-VALUE-CALL
           #:MULTIPLE-VALUE-CALL-ARGUMENTS
           #:MULTIPLE-VALUE-CALL-FUNCTION
           #:MULTIPLE-VALUE-LIST
           #:MULTIPLE-VALUE-PROG1
           #:MULTIPLE-VALUE-PROG1-FORMS
           #:MULTIPLE-VALUE-PROG1-VALUES-FORM
           #:MULTIPLE-VALUE-SETQ
           #:MULTIPLE-VALUES-LIMIT
           #:NAME-CHAR
           #:NAMESTRING
           #:NAND
           #:NBUTLAST
           #:NCONC
           #:NEGATIVE?
           #:NEWLINE
           #:NEXT-METHOD-P
           #:NICKNAME-PACKAGE
           #:NIL
           #:NINTERSECTION
           #:NINTH
           #:NO-APPLICABLE-METHOD
           #:NO-COMPILE
           #:NO-NEXT-METHOD
           #:NOR
           #:NOT
           #:NOTANY
           #:NOTEVERY
           #:NOTINLINE
           #:NRECONC
           #:NREVERSE
           #:NSET-DIFFERENCE
           #:NSET-EXCLUSIVE-OR
           #:NSTRING-CAPITALIZE
           #:NSTRING-DOWNCASE
           #:NSTRING-UPCASE
           #:NSUBLIS
           #:NSUBST
           #:NSUBST-IF
           #:NSUBST-IF-NOT
           #:NSUBSTITUTE
           #:NSUBSTITUTE-IF
           #:NSUBSTITUTE-IF-NOT
           #:NTH
           #:NTH-VALUE
           #:NTHCDR
           #:NULL
           #:NULL?
           #:NUMBER
           #:NUMBER->STRING
           #:NUMBER?
           #:NUMBERP
           #:NUMERATOR
           #:NUNION
           #:OBJECT-DOCUMENTATION-SOURCE
           #:ODD?
           #:ODDP
           #:OPEN
           #:OPEN-STREAM-P
           #:OPTIMIZE
           #:OR
           #:ORDERED-LIST
           #:ORMAP
           #:OTHERWISE
           #:OUTPUT-STREAM-P
           #:PACKAGE
           #:PACKAGE-DEFINED-AND-EXPORTED-SYMBOLS
           #:PACKAGE-DELETE
           #:PACKAGE-DEPENDENCIES
           #:PACKAGE-ERROR
           #:PACKAGE-ERROR-PACKAGE
           #:PACKAGE-EXPORT
           #:PACKAGE-EXPORTED-SYMBOLS
           #:PACKAGE-EXTERNAL-SYMBOLS
           #:PACKAGE-EXTERNAL-SYMBOLS-FROM
           #:PACKAGE-FILE-CONTENTS
           #:PACKAGE-FIND
           #:PACKAGE-HIERARCHY
           #:PACKAGE-IMPORT-FROM
           #:PACKAGE-IMPORT-FROMS
           #:PACKAGE-IMPORTED-SYMBOLS
           #:PACKAGE-NAME
           #:PACKAGE-NICKNAMES
           #:PACKAGE-NON-SHADOWING-SYMBOLS
           #:PACKAGE-RE-EXPORT-SHADOWING
           #:PACKAGE-SHADOW
           #:PACKAGE-SHADOWING-EXPORT
           #:PACKAGE-SHADOWING-IMPORT-FROM
           #:PACKAGE-SHADOWING-IMPORT-FROMS
           #:PACKAGE-SHADOWING-SYMBOLS
           #:PACKAGE-SYMBOLS
           #:PACKAGE-UNUSED-SYMBOLS
           #:PACKAGE-USE
           #:PACKAGE-USE-AND-EXPORT-SHADOWING
           #:PACKAGE-USE-LIST
           #:PACKAGE-USE-SHADOWING
           #:PACKAGE-USED-BY-LIST
           #:PACKAGE-USED-SYMBOLS
           #:PACKAGE?
           #:PACKAGEP
           #:PAIR?
           #:PAIRLIS
           #:PARAGRAPH
           #:PARAMETER?
           #:PARSE-ERROR
           #:PARSE-FUNCTION
           #:PARSE-INTEGER
           #:PARSE-LEXICAL-BODY
           #:PARSE-METADATA-FROM-FUNCTION-BODY
           #:PARSE-NAMESTRING
           #:PARSE-TAGBODY
           #:PARTITION
           #:PATHNAME
           #:PATHNAME-DEVICE
           #:PATHNAME-DIRECTORY
           #:PATHNAME-HOST
           #:PATHNAME-MATCH-P
           #:PATHNAME-NAME
           #:PATHNAME-TYPE
           #:PATHNAME-VERSION
           #:PATHNAMEP
           #:PEEK-CHAR
           #:PHASE
           #:PI
           #:PLUSP
           #:POP
           #:POP-RENDER-PREFIX
           #:POSITION
           #:POSITION-IF
           #:POSITION-IF-NOT
           #:POSITIVE?
           #:PPRINT
           #:PPRINT-DISPATCH
           #:PPRINT-EXIT-IF-LIST-EXHAUSTED
           #:PPRINT-FILL
           #:PPRINT-INDENT
           #:PPRINT-LINEAR
           #:PPRINT-LOGICAL-BLOCK
           #:PPRINT-NEWLINE
           #:PPRINT-POP
           #:PPRINT-TAB
           #:PPRINT-TABULAR
           #:PRIN1
           #:PRIN1-TO-STRING
           #:PRINC
           #:PRINC-TO-STRING
           #:PRINT
           #:PRINT-NOT-READABLE
           #:PRINT-NOT-READABLE-OBJECT
           #:PRINT-OBJECT
           #:PRINT-UNREADABLE-OBJECT
           #:PROBE-FILE
           #:PROCEDURE-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-ALLOW-OTHER-KEYS?
           #:PROCEDURE-ARGUMENTS-KEY-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-OPTIONAL-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REQUIRED-ARGUMENTS
           #:PROCEDURE-ARGUMENTS-REST-ARGUMENT
           #:PROCEDURE-ARITY
           #:PROCEDURE?
           #:PROCLAIM
           #:PROG
           #:PROG*
           #:PROG1
           #:PROG2
           #:PROGN
           #:PROGN-FORMS
           #:PROGRAM-ERROR
           #:PROGV
           #:PROPER-LIST?
           #:PROVIDE
           #:PSETF
           #:PSETQ
           #:PUSH
           #:PUSH-RENDER-PREFIX
           #:PUSHNEW
           #:QUEUE-DELETE!
           #:QUEUE-EMPTY?
           #:QUEUE-FRONT
           #:QUEUE-INSERT!
           #:QUEUE?
           #:QUOTE
           #:QUOTE-EXPR
           #:QUOTIENT
           #:RADIANS->DEGREES
           #:RANDOM
           #:RANDOM-STATE
           #:RANDOM-STATE-P
           #:RANGE
           #:RASSOC
           #:RASSOC-IF
           #:RASSOC-IF-NOT
           #:RATIO
           #:RATIONAL
           #:RATIONALIZE
           #:RATIONALP
           #:RCURRY
           #:READ
           #:READ-BYTE
           #:READ-CHAR
           #:READ-CHAR-NO-HANG
           #:READ-DELIMITED-LIST
           #:READ-FROM-STRING
           #:READ-GUARD-TAG
           #:READ-LINE
           #:READ-PRESERVING-WHITESPACE
           #:READ-SEQUENCE
           #:READER-ERROR
           #:READTABLE
           #:READTABLE-CASE
           #:READTABLEP
           #:REAL
           #:REALP
           #:REALPART
           #:REDUCE
           #:REGISTER-LEXICAL-BODY-DEFINITION
           #:REGISTER-LEXICAL-BODY2-DEFINITION
           #:REGISTERED-DEFINITION-NAME-FIELD
           #:REGISTERED-GUARD-CLAUSES
           #:REINITIALIZE-INSTANCE
           #:REM
           #:REMF
           #:REMHASH
           #:REMOVE
           #:REMOVE*
           #:REMOVE-DUPLICATES
           #:REMOVE-IF
           #:REMOVE-IF-NOT
           #:REMOVE-METHOD
           #:REMPROP
           #:REMQ
           #:REMQ*
           #:RENAME-FILE
           #:RENAME-PACKAGE
           #:RENDER-FRESHLINE
           #:RENDER-HTML-TAG
           #:RENDER-HTML-TAG-TO-STRING
           #:RENDER-INLINE
           #:RENDER-INLINE-ESCAPED
           #:RENDER-LENGTH
           #:RENDER-MARKUP
           #:RENDER-MARKUP-HTML-TAG-TO-STRING
           #:RENDER-MARKUP-TO-STRING
           #:RENDER-NEWLINE
           #:RENDER-PREFIX
           #:RENDER-PREFORMATTED-TEXT
           #:RENDER-WITHOUT-WORD-WRAP
           #:REPEAT
           #:REPLACE
           #:REQUIRE
           #:REST
           #:RESTART
           #:RESTART-BIND
           #:RESTART-CASE
           #:RESTART-NAME
           #:RETURN
           #:RETURN-FROM
           #:RETURN-FROM-NAME
           #:RETURN-FROM-VALUE
           #:REVAPPEND
           #:REVERSE
           #:ROOM
           #:ROTATEF
           #:ROUND
           #:ROW-MAJOR-AREF
           #:RPLACA
           #:RPLACD
           #:SAFE-VECTOR-REF
           #:SAFETY
           #:SATISFIES
           #:SBIT
           #:SCALE-FLOAT
           #:SCHAR
           #:SCM-PARAMETERS->ORDINARY-LAMBDA-LIST
           #:SEARCH
           #:SECOND
           #:SEQ
           #:SEQUENCE
           #:SERIOUS-CONDITION
           #:SET
           #:SET!
           #:SET->STREAM
           #:SET-ADD
           #:SET-CAR!
           #:SET-CDR!
           #:SET-COMPILER-MACRO-DOCUMENTATION-SOURCE!
           #:SET-COUNT
           #:SET-DIFFERENCE
           #:SET-DISPATCH-MACRO-CHARACTER
           #:SET-EMPTY?
           #:SET-EXCLUSIVE-OR
           #:SET-INTERSECT
           #:SET-MACRO-CHARACTER
           #:SET-MEMBER?
           #:SET-OBJECT-DOCUMENTATION-FROM-DOCUMENTATION-SOURCE!
           #:SET-OBJECT-DOCUMENTATION-SOURCE!
           #:SET-PPRINT-DISPATCH
           #:SET-REMOVE
           #:SET-SETF-DOCUMENTATION-SOURCE!
           #:SET-SUBTRACT
           #:SET-SYNTAX-FROM-CHAR
           #:SET-TYPE-DOCUMENTATION-SOURCE!
           #:SET-UNION
           #:SET-VARIABLE-DOCUMENTATION-SOURCE!
           #:SET=?
           #:SETF
           #:SETF-DOCUMENTATION-SOURCE
           #:SETQ
           #:SETQ-PAIRS
           #:SEVENTH
           #:SGN
           #:SHADOW
           #:SHADOWING-IMPORT
           #:SHARED-INITIALIZE
           #:SHIFTF
           #:SHORT-FLOAT
           #:SHORT-FLOAT-EPSILON
           #:SHORT-FLOAT-NEGATIVE-EPSILON
           #:SHORT-SITE-NAME
           #:SIGNAL
           #:SIGNED-BYTE
           #:SIGNUM
           #:SIMPLE-ARRAY
           #:SIMPLE-BASE-STRING
           #:SIMPLE-BIT-VECTOR
           #:SIMPLE-BIT-VECTOR-P
           #:SIMPLE-CONDITION
           #:SIMPLE-CONDITION-FORMAT-ARGUMENTS
           #:SIMPLE-CONDITION-FORMAT-CONTROL
           #:SIMPLE-ERROR
           #:SIMPLE-STRING
           #:SIMPLE-STRING-P
           #:SIMPLE-TYPE-ERROR
           #:SIMPLE-VECTOR
           #:SIMPLE-VECTOR-P
           #:SIMPLE-WARNING
           #:SIN
           #:SINGLE-FLOAT
           #:SINGLE-FLOAT-EPSILON
           #:SINGLE-FLOAT-NEGATIVE-EPSILON
           #:SINH
           #:SIXTH
           #:SLEEP
           #:SLOT-BOUNDP
           #:SLOT-EXISTS-P
           #:SLOT-MAKUNBOUND
           #:SLOT-MISSING
           #:SLOT-UNBOUND
           #:SLOT-VALUE
           #:SOFTWARE-TYPE
           #:SOFTWARE-VERSION
           #:SOME
           #:SORT
           #:SPACE
           #:SPECIAL
           #:SPECIAL-OPERATOR-P
           #:SPEED
           #:SPLIT-AT
           #:SPLIT-STRING
           #:SPLIT-STRING-IF
           #:SPLITF
           #:SQR
           #:SQRT
           #:STABLE-SORT
           #:STANDARD
           #:STANDARD-CHAR
           #:STANDARD-CHAR-P
           #:STANDARD-CLASS
           #:STANDARD-GENERIC-FUNCTION
           #:STANDARD-METHOD
           #:STANDARD-OBJECT
           #:STEP
           #:STORAGE-CONDITION
           #:STORE-VALUE
           #:STREAM
           #:STREAM->LIST
           #:STREAM-APPEND
           #:STREAM-CAR
           #:STREAM-CDR
           #:STREAM-COLLECT
           #:STREAM-CONS
           #:STREAM-DROP
           #:STREAM-ELEMENT-TYPE
           #:STREAM-EMPTY?
           #:STREAM-ERROR
           #:STREAM-ERROR-STREAM
           #:STREAM-EXTERNAL-FORMAT
           #:STREAM-FILTER
           #:STREAM-FIRST
           #:STREAM-FLATMAP
           #:STREAM-FLATTEN
           #:STREAM-FOLD
           #:STREAM-FOR-EACH
           #:STREAM-LENGTH
           #:STREAM-MAP
           #:STREAM-MAP-SUCCESSIVE
           #:STREAM-RANGE
           #:STREAM-REF
           #:STREAM-REST
           #:STREAM-TAKE
           #:STREAM?
           #:STREAMP
           #:STRING
           #:STRING->LIST
           #:STRING-APPEND
           #:STRING-APPEND*
           #:STRING-CAPITALIZE
           #:STRING-DOWNCASE
           #:STRING-EMPTY?
           #:STRING-EQUAL
           #:STRING-FOR-EACH
           #:STRING-GREATERP
           #:STRING-LEFT-TRIM
           #:STRING-LESSP
           #:STRING-MAP
           #:STRING-NOT-EQUAL
           #:STRING-NOT-GREATERP
           #:STRING-NOT-LESSP
           #:STRING-RIGHT-TRIM
           #:STRING-STARTS-WITH?
           #:STRING-STREAM
           #:STRING-TRIM
           #:STRING-UPCASE
           #:STRING/=
           #:STRING<
           #:STRING<=
           #:STRING=
           #:STRING>
           #:STRING>=
           #:STRING?
           #:STRINGP
           #:STRUCT
           #:STRUCT->LIST
           #:STRUCT-ACCESSORS
           #:STRUCT-COPY
           #:STRUCT?
           #:STRUCTURE
           #:STRUCTURE-CLASS
           #:STRUCTURE-OBJECT
           #:STYLE-WARNING
           #:SUBLIS
           #:SUBSEQ
           #:SUBSET?
           #:SUBSETP
           #:SUBST
           #:SUBST-IF
           #:SUBST-IF-NOT
           #:SUBSTITUTE
           #:SUBSTITUTE-IF
           #:SUBSTITUTE-IF-NOT
           #:SUBTYPEP
           #:SVREF
           #:SWAP-ARGS
           #:SXHASH
           #:SYMBOL
           #:SYMBOL->STRING
           #:SYMBOL-FUNCTION
           #:SYMBOL-IN-PACKAGE?
           #:SYMBOL-MACROLET
           #:SYMBOL-MACROLET-BINDINGS
           #:SYMBOL-MACROLET-BODY
           #:SYMBOL-MACROLET-BODY-DECLARATIONS
           #:SYMBOL-MACROLET-BODY-FORMS
           #:SYMBOL-NAME
           #:SYMBOL-PACKAGE
           #:SYMBOL-PLIST
           #:SYMBOL-VALUE
           #:SYMBOL?
           #:SYMBOLICATE
           #:SYMBOLP
           #:SYMBOLS-IN-PACKAGE
           #:SYMBOLS-INTERNED-IN-PACKAGE
           #:SYNONYM-STREAM
           #:SYNONYM-STREAM-SYMBOL
           #:T
           #:TABLE
           #:TAGBODY
           #:TAGBODY-TAGS-AND-STATEMENTS
           #:TAILP
           #:TAKE
           #:TAKEF
           #:TAN
           #:TANH
           #:TENTH
           #:TERPRI
           #:TEXT-RENDERER
           #:TEXT-RENDERER-COPY-WITH-NEW-STREAM
           #:TEXT-RENDERER-POP-PREFIX
           #:TEXT-RENDERER-PUSH-PREFIX
           #:TEXT-RENDERER-RENDER-FRESHLINE
           #:TEXT-RENDERER-RENDER-INLINE
           #:TEXT-RENDERER-RENDER-NEWLINE
           #:TEXT-RENDERER-RENDER-PREFIX
           #:TEXT-RENDERER-RENDER-PREFORMATTED-TEXT
           #:TEXT-RENDERER-RENDER-WITHOUT-WORD-WRAP
           #:TEXT-RENDERER?
           #:THE
           #:THE-FORM
           #:THE-VALUE-TYPE
           #:THERE-EXISTS
           #:THERE-EXISTS*
           #:THIRD
           #:THROW
           #:THROW-RESULT
           #:THROW-TAG
           #:TIME
           #:TRACE
           #:TRANSFORM
           #:TRANSFORM-EXPRESSION
           #:TRANSFORM-IN-LEXICAL-ENVIRONMENT
           #:TRANSFORM-LEXICAL-BODY-DEFINE-DESTRUCTURING
           #:TRANSFORM-LEXICAL-BODY-DEFINE-SYMBOL-OR-PAIR
           #:TRANSFORM-LEXICAL-BODY-DEFINE-VALUES
           #:TRANSFORM-LEXICAL-BODY2-DEFINE-SYMBOL-OR-PAIR
           #:TRANSFORMER
           #:TRANSFORMER-TRANSFORM-ATOM
           #:TRANSFORMER-TRANSFORM-CYCLIC-LIST
           #:TRANSFORMER-TRANSFORM-DOTTED-LIST
           #:TRANSFORMER-TRANSFORM-PROPER-LIST
           #:TRANSFORMER-TRANSFORM-SPECIAL-FORM-TABLE
           #:TRANSFORMER?
           #:TRANSLATE-LOGICAL-PATHNAME
           #:TRANSLATE-PATHNAME
           #:TREE-EQUAL
           #:TRUENAME
           #:TRUNCATE
           #:TWO-WAY-STREAM
           #:TWO-WAY-STREAM-INPUT-STREAM
           #:TWO-WAY-STREAM-OUTPUT-STREAM
           #:TYPE
           #:TYPE-DOCUMENTATION-SOURCE
           #:TYPE-ERROR
           #:TYPE-ERROR-DATUM
           #:TYPE-ERROR-EXPECTED-TYPE
           #:TYPE-OF
           #:TYPECASE
           #:TYPEP
           #:UNBOUND-SLOT
           #:UNBOUND-SLOT-INSTANCE
           #:UNBOUND-VARIABLE
           #:UNDEFINE
           #:UNDEFINE-BUNDLE-PRINT-OBJECT
           #:UNDEFINED-FUNCTION
           #:UNEXPORT
           #:UNINSTALL-SYNTAX!
           #:UNINTERN
           #:UNINTERNED
           #:UNION
           #:UNIQUE-SYMBOL
           #:UNLESS
           #:UNORDERED-LIST
           #:UNREAD-CHAR
           #:UNREGISTER-LEXICAL-BODY-DEFINITION
           #:UNREGISTER-LEXICAL-BODY2-DEFINITION
           #:UNSIGNED-BYTE
           #:UNTRACE
           #:UNUSE-PACKAGE
           #:UNWIND-PROTECT
           #:UNWIND-PROTECT-CLEANUP
           #:UNWIND-PROTECT-PROTECTED
           #:UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
           #:UPDATE-INSTANCE-FOR-REDEFINED-CLASS
           #:UPGRADED-ARRAY-ELEMENT-TYPE
           #:UPGRADED-COMPLEX-PART-TYPE
           #:UPPER-CASE-P
           #:USE-PACKAGE
           #:USE-VALUE
           #:USER-HOMEDIR-PATHNAME
           #:VALUES
           #:VALUES-LIST
           #:VARIABLE
           #:VARIABLE-DOCUMENTATION-SOURCE
           #:VECTOR
           #:VECTOR->LIST
           #:VECTOR-POP
           #:VECTOR-PUSH
           #:VECTOR-PUSH-EXTEND
           #:VECTOR-REF
           #:VECTOR-SET!
           #:VECTORP
           #:WARN
           #:WARNING
           #:WHEN
           #:WILD-PATHNAME-P
           #:WITH-ACCESSORS
           #:WITH-COMPILATION-UNIT
           #:WITH-CONDITION-RESTARTS
           #:WITH-GUARD-CLAUSES-DISABLED
           #:WITH-GUARD-CLAUSES-ENABLED
           #:WITH-HASH-TABLE-ITERATOR
           #:WITH-INPUT-FROM-STRING
           #:WITH-OPEN-FILE
           #:WITH-OPEN-STREAM
           #:WITH-OUTPUT-TO-STRING
           #:WITH-PACKAGE-ITERATOR
           #:WITH-READABLE-SYMBOLS
           #:WITH-SIMPLE-RESTART
           #:WITH-SLOTS
           #:WITH-STANDARD-IO-SYNTAX
           #:WITH-TEMPORARY-PACKAGE
           #:WORD-WRAP-LINE
           #:WRITE
           #:WRITE-BYTE
           #:WRITE-CHAR
           #:WRITE-LINE
           #:WRITE-SEQUENCE
           #:WRITE-STRING
           #:WRITE-TO-STRING
           #:XOR
           #:Y-OR-N-P
           #:YES-OR-NO-P
           #:ZERO?
           #:ZEROP)
  (:NICKNAMES #:SCHEMEISH #:SCM))

